C CTENI JEDNOHO RADKU RIDKE SOUSTAVY A*X=B ZE VSTUPNIHO ZARIZENI
C=======================================================================
C
      SUBROUTINE GTGETR(LUN,NONZ,INDC,ROW,ABSCL,W,IOUT)
C
C$INCLUDE: 'GTREAL.INC'
      DOUBLE PRECISION
     /         ROW(1), ABSCL, W
      INTEGER  LUN, NONZ, INDC(1), IOUT
      INTEGER  POCNEZ, POCMER
C
C LUN     CISLO VSTUPNIHO LOGICKEHO ZARIZENI
C NONZ    POCET NENULOVYCH PRVKU V RADKU
C INDC    INDEXY NACTENYCH NENULOVYCH PRVKU
C ROW     NENULOVE PRVKY NACTENEHO RADKU
C ABSCL   ABSOLUTNI CLEN
C IOUT    VYSTUPNI PARAMETR:
C         IOUT =  0  NACTENY NENULOVE PRVKY
C              = -1  KONEC VSTUPNIHO SOUBORU
C              = -2  CHYBA VE VSTUPNICH DATECH
C
C-----------------------------------------------------------------------
C
C INICIALIZACI PROCEDURY GTGETR ZAJISTUJE MODUL GTGET0, KTERY VRACI
C POCET POCET NEZNAMYCH A POCET MERENI (RADKU MATICE) A NASTAVI VSTUPNI
C SOUBOR NA POCATEK.
C
C VOLANI:   CALL GTGET0(LUN, POCNEZ, POCMER)
C
C-----------------------------------------------------------------------
C
C NENULOVE PRVKY JEDNOHO RADKU RIDKE MATICE SE ZAPISUJI V NASLEDUJICIM
C FORMATU (DVA ZAZNAMY PRO KAZDY RADEK):
C
C POCET NENULYCH PRVKU, SEZNAM INDEXU NENULOVYCH PRVKU
C VAHA,  ABSOLUTNI CLEN, SEZNAM NENULOVYCH PRVKU
C
C SEZNAM NENULOVYCH PRVKU PROCEDURA HOMOGENIZUJE (KAZDY NENULOVY PRVEK
C JE VYNASOBEN ODMOCNINOU Z VAHY)
C
C-----------------------------------------------------------------------
C
C$INCLUDE: 'GTREAL.INC'
      DOUBLE PRECISION
     /         ODMV
      INTEGER  I
      REAL     PW, PABSCL, PROW(100)
C
C     READ(LUN,END=901,ERR=902)  NONZ, (INDC(I),I=1,NONZ)
      READ(LUN,*,END=901,ERR=902)  NONZ, (INDC(I),I=1,NONZ)
      IF(NONZ.LE.0)  GOTO 902
C     READ(LUN,END=901,ERR=902)  PW, PABSCL, (PROW(I), I=1,NONZ)
      READ(LUN,*,END=901,ERR=902)  PW, PABSCL, (PROW(I), I=1,NONZ)
      W = PW
      IF(W.LE.0)  GOTO 902
      ODMV = SQRT(W)
      DO 100 I=1,NONZ
         ROW(I) = PROW(I)*ODMV
100   CONTINUE
      ABSCL = PABSCL*ODMV
      IOUT = 0
      RETURN
C
901   IOUT = -1
      RETURN
902   IOUT = -2
      RETURN
C
      ENTRY GTGET0(LUN, POCNEZ, POCMER, IOUT)
C
      REWIND LUN
C     READ(LUN,END=902,ERR=902)  POCNEZ, POCMER
      READ(LUN,*,END=902,ERR=902)  POCNEZ, POCMER
      IF(POCNEZ.LE.0 .OR. POCMER.LE.0)  GOTO 902
      IOUT = 0
      RETURN
C
      END
