C VYPOCET RADKOVE NORMY MATICE SOUSTAVY ROVNIC OPRAV
C=======================================================================
C
      SUBROUTINE GTMNOR(LUN,RNORM,SNORM,WW,IOUT)
C
C LUN    CISLO LOGICKEHO ZARIZENI PRO CTENI MATICE
C RNORM  RADKOVA NORMA MATICE
C SNORM  SLOUPCOVA NORMA
C WW     PRACOVNI POLE (DIMENZE POCNEZ)
C IOUT   = -1 NORMALNI UKONCENI PROCEDURY
C        = -2 CHYBA PRI CTENI VSTUPNI MATICE
C
      INTEGER  LUN,IOUT
C$INCLUDE: 'GTREAL.INC'
      DOUBLE PRECISION
     /         RNORM, SNORM, WW(1)
      INTEGER  NONZ, INDC(100), POCNEZ, POCPOZ, I, J
C$INCLUDE: 'GTREAL.INC'
      DOUBLE PRECISION
     /         ROW(100), ABSCL, W, S
C
      CALL GTGET0(LUN,POCNEZ,POCPOZ,IOUT)
      IF(IOUT.NE.0)  RETURN
      RNORM = 0.0
      DO 10 I=1,POCNEZ
         WW(I) = 0.0
10    CONTINUE
100   CALL GTGETR(LUN,NONZ,INDC,ROW,ABSCL,W,IOUT)
         IF(IOUT.LT.0)  GOTO 199
         S = 0.0
         DO 110 I=1,NONZ
            S = S + ABS(ROW(I))
            J = INDC(I)
            WW(J) = WW(J) + ABS(ROW(I))
110      CONTINUE
         IF(S.GT.RNORM)  RNORM = S
         GOTO 100
199   CONTINUE
      SNORM = 0.0
      DO 200 I=1,POCNEZ
         IF(WW(I).GT.SNORM)  SNORM = WW(I)
200   CONTINUE
      RETURN
C
      END
