C ANALYZA A TISK NEZNAMYCH A JEJICH FUNKCI (NEMERENE NEZNAME)
C=======================================================================
C         1. VERZE  /ZARI 1984/         VUGTK
C
      SUBROUTINE GDTANN(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      INTEGER  IOUT
      LOGICAL  TISK
C
      TISK = .TRUE.
0102  CONTINUE
      CALL GDTAN1(TISK,3,IOUT)
C VYPIS PREHLEDU NEZNAMYCH
      IF(IOUT.EQ.1)  CALL GDTVPN(AW)
C VYPIS PREHL.STR.CHYB A ELIPS CH.
      IF(IOUT.EQ.2)  CALL GDTELI(AW)
C VYPIS SEZNAMU SOURADNIC
      IF(IOUT.EQ.3)  CALL GDTSSO(AW)
C VYP.SEZ. VYROV. DELEK A SMERNIKU
      IF(IOUT.EQ.4)  CALL GDTSDS(AW)
C VYPIS SMERNIKU
      IF(IOUT.EQ.5)  CALL GDTSME(AW)
C VYPOCET MATICE VAH. KOEF.
      IF(IOUT.EQ.6)  CALL GDTQYX(AW)
      IF(IOUT.EQ.-2)  GOTO 0199
      GOTO 0102
0199  CONTINUE
C
      END
