C TISK HLAVICKY VYPISU MERENYCH PRVKU, ABS. CLENU A VAH
C=======================================================================
C         1. VERZE  /SRPEN 1984/         VUGTK
C
      SUBROUTINE GDTA41(LUN)
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  LUN
C
      IF(LUN.EQ.GSGDPT)  CALL GDSSTR(2,0)
      WRITE(LUN,1)
1     FORMAT(1X,
     /'  STANOVISKO',12X,'CIL   T  MER.DELKA[M]   ABS. CLEN      VAHA'/
     /1X,24('='),         '======== /OR.SMER [G] == [MM/CC] ',13('=') )
      RETURN
C
      END
C TISK TYPU JEDNOTKOVE STREDNI CHYBY A KONFIDENCNI PRAVDEPODOBNOSTI
C=======================================================================
C         1. VERZE  /ZARI 1984/         VUGTK
C
      SUBROUTINE GDTA49
C
$INCLUDE: 'GDTSOW.COM'
C
      CALL GDSSTR(3,0)
      WRITE(GSGDPT,1)  TYPM0,M0AKT,PRST
      CALL TTROL1(ITT,1)
      WRITE(ITT   ,1)  TYPM0,M0AKT,PRST
1     FORMAT(
     /' PRI STATISTICKE ANALYZE SE PRACUJE'/
     /' - S ',8A1, ' JEDNOTKOVOU STREDNI CHYBOU',F8.2,' [MM/CC]'/
     /' - S KONFIDENCNI PRAVDEPODOBNOSTI       ',F8.2,' %')
C
      END
C AKTUALIZACE INFORMACI O MERENYCH PRVCICH
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C
      SUBROUTINE GDTA4S(TISK,IOP)
C
$INCLUDE: 'GDTSOW.COM'
      LOGICAL  TISK
      INTEGER  IOP,LOUT
4     FORMAT(' 4 ... AKTUALIZACE INFORMACI O MERENYCH PRVCICH')
      IF(SS.LT.2)  RETURN
0103  IF(.NOT.TISK)  GOTO 0199
         WRITE(ITT,4)
         RETURN
0199  CONTINUE
      IF(IOP.NE.4)  RETURN
      CALL TTZAHL(ITT,'AKTUALIZACE INFORMACI O MERENYCH PRVCICH:')
      WRITE(ITT,1)
1     FORMAT(
     /' 1 ... ZMENY JEDNOTLIVYCH PRVKU'/
     /' 2 ... GLOBALNI ZMENY STREDNICH CHYB'/)
      CALL GDTPPK('ZVOL TYP AKTUALIZACE (1-2): ',LOUT)
      CALL TTROL1(ITT,2)
      IF(LOUT.EQ.1)  CALL GDTA4T
      IF(LOUT.EQ.2)  CALL GDTGZS
C
      END
C ZMENA JEDNOTLIVYCH PRVKU V SEZMER
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C       * 5. VERZE      /ZARI 1989/             VUGTK      ALES CEPEK
C
      SUBROUTINE GDTA4T
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  ISTA,ICIL,ITYP,IPRV,IPOM,IPOR,I,INDEX,IOUT
      PARAMETER  (IPOM= 62)
      LOGICAL  EOF,ZMENA
      DOUBLE PRECISION  DPOM
      INTEGER*1  BSTA(13),BCIL(13),TYP,VYZVA(IPOM),TEXT(38),TPRV(5)
      EQUIVALENCE  (VYZVA,TPRV)
      CHARACTER*(IPOM) CVYZVA
      EQUIVALENCE (CVYZVA,VYZVA)
      CHARACTER*38 CTEXT
      EQUIVALENCE (CTEXT,TEXT)
1     FORMAT(
     /' DUPLICITA - IDENTIFIKUJ PRVEK PORADOVYM CISLEM (1 -',I6,'): ')
2     FORMAT('       ',13A1,' --> ',13A1)
3     FORMAT(/1X,38A1/' = INDEX ',31('='))
4     FORMAT(
     /'    1    DELKA      [M] :',F12.5/
     /'    2    STR. CHYBA [MM]:',F9.2)
5     FORMAT(
     /'    1    SMER       [G] :',F12.6/
     /'    2    STR. CHYBA [CC]:',F8.2 )
6     FORMAT(
     /'    3    CHAR. ZAMERY   :',I6)
31    FORMAT(' AKTUALIZOVANY PRVEK: ',70A1)
C
0102  CONTINUE
      ZMENA = .FALSE.
      CALL TTROL1(ITT,2)
      CALL GDTSCP('STANOVISKO : ',BSTA,ISTA,EOF)
      IF(EOF)  GOTO 0199
      CALL GDTSCP('CIL        : ',BCIL,ICIL,EOF)
      IF(EOF)  GOTO 0199
      CALL GDSDAN('TYP MERENEHO PRVKU (D/S): ',ITYP)
      TYP = 'D'
      IF(ITYP.EQ.2)  TYP = 'S'
      CALL GDTHPR(ISTA,ICIL,TYP,IPRV,0)
0203  IF(IPRV.NE.0)  GOTO 0204
         CALL TTPUT1(ITT,1,'NEEXISTUJICI PRVEK SITE:')
         GOTO 0102
0204  IF(IPRV.EQ.1)  GOTO 0205
C*       ENCODE(IPOM-1,1,VYZVA)  IPRV
         WRITE(CVYZVA,1) IPRV
         VYZVA(IPOM) = 0
         CALL GDSMEZ(VYZVA,IPOM,IPOR)
         CALL GDSDAN(VYZVA,IPOR)
         GOTO 0299
0205  CONTINUE
         IPOR = 1
0299  CONTINUE
      CALL GDTHPR(ISTA,ICIL,TYP,IPRV,IPOR)
C*    ENCODE(38,2,TEXT)  BSTA,BCIL
      WRITE(CTEXT,2) BSTA,BCIL
      CALL GDSMEZ(TEXT,38,I)
      IF(TYP.EQ.'S')  CALL SCOPY('SMER : 'C,VYZVA)
      IF(TYP.EQ.'D')  CALL SCOPY('DELKA: 'C,VYZVA)
0302  WRITE(ITT,3)  TEXT
      IF(TYP.EQ.'D')  WRITE(ITT,4)  PRVEK(IPRV),STRCH(IPRV)
      IF(TYP.EQ.'S')  WRITE(ITT,5)  PRVEK(IPRV)*RO,STRCH(IPRV)
       IF(CHAZ(IPRV).GT.0)  WRITE(ITT,6)  CHAZ(IPRV)
      IF(CHAZ(IPRV).LE.0)  WRITE(ITT,6)
      CALL TTASK(ITT,'INDEX (1-3): ',INDEX)
      IF(INDEX.EQ.0.OR.INDEX.EQ.-1)  GOTO 0302
0403  IF(INDEX.NE.1)  GOTO 0404
0502     CALL TTASKD(ITT,VYZVA,IOUT,DPOM,1)
         IF(IOUT.EQ.0.OR.IOUT.EQ.-2)   GOTO 0302
         IF(IOUT.LT.0)   GOTO 0502
0603     IF(TYP.NE.'S')  GOTO 0604
            IF(DPOM.LT.0)  DPOM = DPOM + 400
            IF(ABS(DPOM).GE.400)  GOTO 0502
            IF(DPOM.LT.0)  GOTO 0502
            DPOM = DPOM/RO
            GOTO 0699
0604     CONTINUE
            IF(DPOM.LE.0)  GOTO 0502
            IF(DPOM.GT.1D7)  GOTO 0502
0699     CONTINUE
         PRVEK(IPRV) = DPOM
         ZMENA = .TRUE.
         SS = MIN(SS,2)
         GOTO 0499
0404  IF(INDEX.NE.2)  GOTO 0405
0702     CALL TTASKD(ITT,'STR. CHYBA: ',IOUT,DPOM,1)
         IF(IOUT.EQ.0.OR.IOUT.EQ.-2)  GOTO 0302
         IF(IOUT.LE.0)  GOTO 0702
         IF(DPOM.LE.0)  GOTO 0702
         IF(DPOM.GT.1D7)  GOTO 0702
         STRCH(IPRV) = DPOM
         ZMENA = .TRUE.
         SS = MIN(SS,3)
         GOTO 0499
0405  IF(INDEX.NE.3)  GOTO 0499
0802     CALL TTASKN(ITT,'CHAR. ZAMERY: ',IOUT,IPOR,1)
         IF(IOUT.EQ.0.OR.IOUT.EQ.-2)  GOTO 0302
         IF(IPOR.LT.0.OR.IPOR.GT.127) GOTO 0802
         CHAZ(IPRV) = IPOR
         ZMENA = .TRUE.
0499  CONTINUE
0399  IF(INDEX.NE.-2)  GOTO 0302
      IF(.NOT.ZMENA)  GOTO 0102
      CALL GDSSTR(1,0)
      WRITE(GSGDPT,31)  TPRV,TEXT
      GOTO 0102
0199  CONTINUE
C
      END
