C ZADANI NAZVU VARIANTY RESENI A MNOZINY OPERNYCH BODU
C=======================================================================
C         2. VERZE      /RIJEN 1985/         VUGTK      ALES CEPEK
C       * 5. VERZE      /ZARI 1989/             VUGTK      ALES CEPEK
C
      SUBROUTINE GDTAVZ(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      INTEGER  IOUT,I,J,PPBIT1,INEZN,IBOD,INTCB(3),IER,INTPOB
      INTEGER*4  K,POCET
      INTEGER*1  TEXT(72),BOD(13),BOD14(14),INTNAZ(25),INTINT(MAX)
      CHARACTER*72 CTEXT
      EQUIVALENCE (CTEXT,TEXT)
      REAL  VSTUP(ISREC)
      LOGICAL  NOVY
100   FORMAT('/A/MAM BOD ',13A1,' POVAZOVAT ZA OPERNY? (A/N): ')
C
1     CONTINUE
C*    CALL PPINI1(' ',25,INTNAZ)
      DO 9981 II81=1,25
9981     INTNAZ(II81) = ' '
      CALL TTASKS(ITT,'NAZEV VARIANTY RESENI: ',IOUT,INTNAZ,25)
      IF(IOUT.LT.0)  GOTO 1
2     CONTINUE
      CALL GDTPPK(
     /'/N/MAJI BYT VSECHNY URCOVANE BODY POVAZOVANY ZA OPERNE? (A/N): '
     /,IOUT)
      IF(IOUT.EQ.-2) GOTO 1
      IF(IOUT.EQ.2)  GOTO 11
      CALL PPMOV1(1,TYPB,1,INTINT,1,SBPOC)
C VSECHNY URCOVANE BODY JSOU OPERNE
      DO 10 I=1,SBPOC
10    IF(INTINT(I).EQ.'U')  INTINT(I) = 'O'
      INTPOB = URCBOD
      J = 0
      DO 92 I=POCORP+1,POCNEZ
      J = J +1
92    INDX(J) = I
      GOTO 8000
C
11    CONTINUE
      CALL PPMOV1(1,TYPB,1,INTINT,1,SBPOC)
      IF(PPBIT1(PK,3).EQ.0)  GOTO 12
      CALL GDTPPK('/A/POZADUJES NABIDKU CISEL BODU? (A/N): ',IOUT)
      IF(IOUT.EQ.-2) GOTO 2
      IF(IOUT.EQ.2)  GOTO 12
      I = 0
0102  I = I + 1
      IF(I.GT.SBPOC)  GOTO 0199
      IF(INTINT(I).NE.'U')  GOTO 0102
         CALL GDTEXT(I,BOD)
C*       ENCODE(50,100,TEXT)  BOD
         WRITE(CTEXT(:53),100) BOD
         CALL GDSMEZ(TEXT,53,IOUT)
         TEXT(IOUT+1) = 0
         CALL GDTPPK(TEXT,IOUT)
         IF(IOUT.EQ.-2) GOTO 0199
         IF(IOUT.EQ.2)  GOTO 0102
         INTINT(I) = 'O'
         GOTO 0102
0199  CONTINUE
3     CONTINUE
      CALL TTPUT1(ITT,1,'JAKO OPERNE BODY BYLY ZADANY BODY S CISLY:')
      CALL GDTBU1(.FALSE.,.TRUE.)
C INDEX NEZNAME (SOURADNICE Y BEZNEHO BODU)
      INEZN = POCORP - 1
      NXMIN = 0
      INTPOB = 0
      I = 0
0202  I = I + 1
      IF(I.GT.SBPOC)  GOTO 0299
         IF(TYPB(I).EQ.'U')  INEZN = INEZN + 2
         IF(INTINT(I).NE.'O')  GOTO 0202
         INTPOB = INTPOB + 1
         CALL GDTEXT(I,BOD14)
         IBOD = 14
         IF(BOD(13).EQ.' ')  IBOD = 13
         BOD14(IBOD) = ','
         CALL GDTBUF(BOD14,IBOD)
         NXMIN = NXMIN + 1
         INDX(NXMIN) = INEZN
         NXMIN = NXMIN + 1
         INDX(NXMIN) = INEZN + 1
         GOTO 0202
0299  CONTINUE
      CALL GDTBU2(1)
      IF(2*INTPOB.LT.DEFEKT)  GOTO 13
      CALL TTROL1(ITT,1)
      CALL GDTPPK('/A/SOUHLASIS S TOUTO VOLBOU OPERNYCH BODU? (A/N): ',
     /IOUT)
      IF(IOUT.EQ.2.OR.IOUT.EQ.-2)  GOTO 2
      GOTO 8000
C
13    CONTINUE
      CALL TTPUT1(ITT,1,'POCET OPERNYCH BODU JE NEDOSTATECNY.:')
131   CALL GDTPPK('/A/BUDES DEFINOVAT NOVOU VARIANTU RESENI? (A/N): ',
     /IOUT)
      IF(IOUT.EQ.1)  GOTO 1
      IF(IOUT.NE.2)  GOTO 131
      KK = 2
      RETURN
C
12    CONTINUE
      CALL TTASKS(ITT,'CISLO OPERNEHO BODU: ',IOUT,TEXT,15)
      IF(IOUT.EQ.-2) GOTO 3
      IF(IOUT.LE.0)  GOTO 12
      CALL GDSKCB(1,TEXT,15,INTCB,IER)
0503  IF(IER.EQ.0)  GOTO 0599
         CALL TTPUT1(ITT,0,'CHYBNA SPECIFIKACE CISLA BODU:')
         GOTO 12
0599  CONTINUE
      CALL GDTHCB(INTCB,I,.FALSE.,NOVY)
0303  IF(.NOT.(NOVY.OR.TYPB(I).EQ.' '))  GOTO 0399
         CALL TTPUT1(ITT,0,'NEEXISTUJICI BOD:')
         GOTO 12
0399  CONTINUE
0403  IF(TYPB(I).NE.'P')  GOTO 0499
         CALL TTPUT1(ITT,0,'PEVNY BOD NELZE PROHLASIT ZA OPERNY:')
         GOTO 12
0499  CONTINUE
      INTINT(I) = 'O'
      GOTO 12
C
8000  CONTINUE
      KK = 1
      CALL PPMOV1(1,INTNAZ,1,NAZVAR,1,25)
      CALL PPMOV1(1,INTINT,1,INTERT,1,MAX)
      POB = INTPOB
      POCET = MARED
      POCET = POCET*NARED
C CITAC ZAZNAMU V SOUBORU IS
      J = SOWREC
C CITAC PRVKU V POLI AW
      K = 0
8102  J = J + 1
      READ(GSGDIS,REC=J)  VSTUP
      DO 8100 I=1,ISREC
      K = K + 1
      IF(K.GT.POCET)  GOTO 8199
8100  AW(K) = VSTUP(I)
C *** 2
      IF(K.LT.POCET)  GOTO 8102
8199  CONTINUE
      RETURN
C
      END
