C ZMENA MNOZINY MERENYCH PRVKU
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C
      SUBROUTINE GDTA2S(TISK,IOP)
C
$INCLUDE: 'GDTSOW.COM'
      LOGICAL  TISK
      INTEGER  IOP
1     FORMAT(/' TYP ZMENY: '/
     /' 1 ... VYMAZ PRVKU'/
     /' 2 ... DOPLNENI PRVKU Z KLAVESNICE'/
     /)
2     FORMAT(' 2 ... ZMENA MNOZINY MERENYCH PRVKU')
C
      IF(SS.LT.1)  RETURN
0103  IF(.NOT.TISK)  GOTO 0199
         WRITE(ITT,2)
         RETURN
0199  CONTINUE
      IF(IOP.NE.2)  RETURN
      CALL TTZAHL(ITT,'ZMENA MNOZINY MERENYCH PRVKU:')
0202  CONTINUE
         WRITE(ITT,1)
         CALL TTASK(ITT,'ZVOL TYP ZMENY (1-2): ',IOUT)
         IF(IOUT.EQ.-2)  RETURN
         IF(IOUT.EQ.1.AND.POCPOZ.LE.0)  GOTO 0202
0299  IF(IOUT.LE.0)  GOTO 0202
      IF(IOUT.EQ.1)  CALL GDTA2T
      IF(IOUT.EQ.2)  CALL GDTA2U
      CALL GDTKON
      RETURN
C
      END
C VYMAZ PRVKU V SEZMER
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C       * 5. VERZE      /ZARI 1989/             VUGTK      ALES CEPEK
C
      SUBROUTINE GDTA2T
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  IOUT,I,ISTA,ICIL,IPOM,IPAR
      LOGICAL  EOF,VYMAZ
      PARAMETER  (IPAR=37)
      INTEGER*1  BSTA(13),BCIL(13),BPRV(IPAR),BCHA(13)
      CHARACTER CBPRV*(IPAR),CBCHA*13
      EQUIVALENCE (CBPRV,BPRV),(CBCHA,BCHA)
      DOUBLE PRECISION  PRV
      REAL  STR
1     FORMAT(' VYRAZENY VSECHNY SMERY/DELKY')
2     FORMAT(' ZRUSENY VSECHNY ORIENTACNI POSUNY')
3     FORMAT(' DUPLICITNI PRVEK:',I4)
4     FORMAT('DELKA ',13A1,' --> ',13A1)
5     FORMAT(' VYRAZENY PRVEK: ',70A1)
C*6   FORMAT(I<13-1-IFR>,<IFR+1>X)
C*7   FORMAT(/
C*   /' ZAMERA: ',<IPAR>A1/<9+IPAR>('=')/
C*   /' DELKA/SMER   :',F13.<IFR>,' [M/G]'/
C*   /' STREDNI CHYBA:',F13.<IFR>/
C*   /' CHAR. ZAMERY :',13A1/)
6     FORMAT(I7,6X)
7     FORMAT(/
     /' ZAMERA: ',37A1/46('=')/
     /' DELKA/SMER   :',F13.5,' [M/G]'/
     /' STREDNI CHYBA:',F13.5/
     /' CHAR. ZAMERY :',13A1/)
8     FORMAT(I6,7X)
9     FORMAT(/
     /' ZAMERA: ',37A1/46('=')/
     /' DELKA/SMER   :',F13.6,' [M/G]'/
     /' STREDNI CHYBA:',F13.6/
     /' CHAR. ZAMERY :',13A1/)
      VYMAZ = .FALSE.
0202  CONTINUE
      CALL TTROL1(ITT,2)
      CALL GDTPPK('TYP MERENEHO PRVKU (D/S): ',IOUT)
      IF(IOUT.EQ.-2) GOTO 0299
      TYP = 'D'
      IF(IOUT.EQ.2)  TYP = 'S'
      CALL GDTSCP('STANOVISKO: ',BSTA,ISTA,EOF)
      IF(EOF)  GOTO 0202
      CALL GDTSCP('CIL       : ',BCIL,ICIL,EOF)
      IF(EOF)  GOTO 0202
      CALL GDTHPR(ISTA,ICIL,TYP,IPOM,0)
0303  IF(IPOM.GT.0)  GOTO 0399
         CALL TTPUT1(ITT,1,'NEEXISTUJICI PRVEK SITE:')
         GOTO 0202
0399  CONTINUE
      IF(IPOM.GT.1)  WRITE(ITT,3)  IPOM
C*    ENCODE(IPAR,4,BPRV)  BSTA,BCIL
      WRITE(CBPRV,4)  BSTA,BCIL
      IF(TYP.EQ.'S')  CALL PPMOV1(1,'SMER  ',1,BPRV,1,6)
      CALL GDSMEZ(BPRV,IPAR,I)
      DO 0400 I=IPOM,1,-1
         CALL GDTHPR(ISTA,ICIL,TYP,IPRV,I)
         PRV = PRVEK(IPRV)
         IF(TYP.EQ.'S')  PRV = PRV*RO
         STR = STRCH(IPRV)
         STR = STR*1E-3
         IF(TYP.EQ.'S')  STR = STR*1E-1
C*       IFR = 5
C*       IF(TYP.EQ.'S')  IFR = 6
C*       ENCODE(13,6,BCHA)  CHAZ(IPRV)
         IF(TYP.EQ.'S') THEN
            WRITE(CBCHA,8) CHAZ(IPRV)
	 ELSE
            WRITE(CBCHA,6) CHAZ(IPRV)
	 END IF
C*       IF(CHAZ(IPRV).LE.0)  CALL PPINI1(' ',13,BCHA)
         IF(CHAZ(IPRV).LE.0) THEN
	    DO 9981 II81=1,13
9981           BCHA(II81) = ' '
         END IF	
C*       WRITE(ITT,7)  BPRV,PRV,STR,BCHA
         IF(TYP.EQ.'S') THEN
            WRITE(ITT,9)  BPRV,PRV,STR,BCHA
         ELSE
            WRITE(ITT,7)  BPRV,PRV,STR,BCHA
         END IF
0402     CALL TTASK(ITT,'/A/MAM MERENY PRVEK ZRUSIT? (A/N): ',IOUT)
         IF(IOUT.EQ.-2) GOTO 0400
         IF(IOUT.LT.0)  GOTO 0402
         IF(IOUT.NE.1)  GOTO 0400
         VYMAZ = .TRUE.
         TYPP(IPRV) = ' '
         CALL GDSSTR(1,0)
         WRITE(GSGDPT,5)  BPRV
0400  CONTINUE
      GOTO 0202
0299  CONTINUE
      IF(VYMAZ)  SS = 2
      RETURN
C
      END
C DOPLNENI MERENYCH PRVKU Z KLAVESNICE
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C       * 5. VERZE      /ZARI 1989/             VUGTK      ALES CEPEK
C
      SUBROUTINE GDTA2U
C
$INCLUDE: 'GDTSOW.COM'
      LOGICAL  ULOZ,EOF
      INTEGER  IOUT,ISTA,ICIL,IPOM,PPBIT1
      INTEGER*1  TYP,BSTA(13),BCIL(13),VYZVA(70),TEXT(54)
      EQUIVALENCE (VYZVA,TEXT)
      CHARACTER*54 CTEXT
      EQUIVALENCE (CTEXT,TEXT)
      DOUBLE PRECISION  DPOM
1     FORMAT(' DOPLNENY PRVEK: DELKA ',13A1,' --> ',13A1)
2     FORMAT(72A1)
C
      CALL TTZAHL(ITT,'DOPLNENI MERENYCH PRVKU Z KLAVESNICE:')
      ULOZ = .FALSE.
0102  CALL TTROL1(ITT,2)
      IF(SMPOC.EQ.MAXMER)  GOTO 9999
      CALL GDTPPK('TYP MERENEHO PRVKU (D/S): ',IOUT)
      IF(IOUT.EQ.-2) GOTO 0199
      TYP = 'D'
      IF(IOUT.EQ.2)  TYP = 'S'
      CALL GDTSCP('STANOVISKO: ',BSTA,ISTA,EOF)
      IF(EOF)  GOTO 0102
      CALL GDTSCP('CIL       : ',BCIL,ICIL,EOF)
      IF(EOF)  GOTO 0102
      CALL GDTHPR(ISTA,ICIL,TYP,IOUT,1)
0203  IF(IOUT.EQ.0)  GOTO 0299
         CALL GDSDAN(
     /   '/N/DUPLICITA - TRVAS NA DOPLNENI PRVKU? (A/N): ',IOUT)
         IF(IOUT.NE.1)  GOTO 0102
0299  CONTINUE
0302  IF(TYP.EQ.'S')  CALL SCOPY('SMER  [G]: 'C,VYZVA)
      IF(TYP.EQ.'D')  CALL SCOPY('DELKA [M]: 'C,VYZVA)
      CALL TTASKD(ITT,VYZVA,IOUT,DPOM,1)
      IF(IOUT.EQ.-2) GOTO 0102
      IF(IOUT.LE.0)  GOTO 0302
      IF(DPOM.LT.0)  GOTO 0302
      IF(TYP.EQ.'S'.AND.DPOM.GE.400)  GOTO 0302
      IF(TYP.EQ.'S')  DPOM = DPOM/RO
      PRVEK(SMPOC+1) = DPOM
      TYPP(SMPOC+1) = TYP
      CST(SMPOC+1) = ISTA
      CCI(SMPOC+1) = ICIL
0402  IF(TYP.EQ.'S')  CALL SCOPY('STREDNI CHYBA [CC]: 'C,VYZVA)
      IF(TYP.EQ.'D')  CALL SCOPY('STREDNI CHYBA [MM]: 'C,VYZVA)
      CALL TTASKD(ITT,VYZVA,IOUT,DPOM,1)
      IF(IOUT.EQ.-2) GOTO 0302
      IF(IOUT.LE.0)  GOTO 0402
      IF(DPOM.LE.0)  GOTO 0402
      IF(DPOM.GT.1D4)  GOTO 0402
      STRCH(SMPOC+1) = DPOM
0502  CALL TTASKN(ITT,'CHARAKTERISTIKA ZAMERY: ',IOUT,IPOM,1)
      IF(IOUT.EQ.-2) GOTO 0402
      IF(IOUT.LT.0)  GOTO 0502
      IF(IOUT.EQ.0)  IPOM = 0
      IF(IPOM.LT.0.OR.IPOM.GT.127)  GOTO 0502
      CHAZ(SMPOC+1) = IPOM
0603  IF(PPBIT1(PK,3).NE.0)  GOTO 0699
         CALL GDTPPK(
     /   '/A/SOUHLASIS SE ZAPISEM PRIPRAVENYCH DAT? (A/N): ',IOUT)
         IF(IOUT.EQ.-2) GOTO 0502
         IF(IOUT.EQ.2)  GOTO 0102
0699  CONTINUE
      SMPOC = SMPOC + 1
      ULOZ  = .TRUE.
C*    ENCODE(54,1,TEXT)  BSTA,BCIL
      WRITE(CTEXT,1) BSTA,BCIL
      IF(TYP.EQ.'S')  CALL PPMOV1(1,'SMER ',1,TEXT,18,5)
      CALL GDSMEZ(TEXT,54,IOUT)
      CALL GDSSTR(1,0)
      WRITE(GSGDPT,2)  TEXT
      GOTO 0102
0199  CONTINUE
9999  IF(SMPOC.EQ.MAXMER)  CALL TTPUT1(ITT,1,
     /'SEZNAM MERENYCH PRVKU JE OBSAZEN - DALSI PRVKY NELZE UKLADAT:')
      IF(ULOZ)  SS = 2
      RETURN
C
      END
