C AKTUALIZACE SOUBORU IS
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C
      SUBROUTINE GDTASI
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  IOP,I,POMPOB
      LOGICAL  TISK
      CHARACTER*(*) RET
      PARAMETER (RET='AKTUALIZACE/VYPIS SOUBORU INFORMACI O SITI:')
C
      CALL GDTTHL(GSGDPT,RET)
      CALL GDTTHL(ITT   ,RET)
C ULOZEN POCET OPERNYCH BODU
      POMPOB = POB
C ULOZENA HODNOTA SS (VIZ PROCEDURU GDTA7S)
      POB = SS
      DO 100 I=1,25
100   NAZVAR(I) = ' '
      IOP = 0
0102  DO 0199 I=1,2
         TISK = I.EQ.1
C ZMENA MNOZINY BODU SITE
         CALL GDTA1S(TISK,IOP)
C ZMENA MNOZINY MERENYCH PRVKU
         CALL GDTA2S(TISK,IOP)
C AKTUALIZACE INF. O BODECH A OR. POS.
         CALL GDTA3S(TISK,IOP)
C AKTUALIZACE INF. O MER. PRVCICH
         CALL GDTA4S(TISK,IOP)
C VYPIS INFORMACI O BODECH A OR. POS.
         CALL GDTA5S(TISK,IOP)
C VYPIS INFORMACI O MER. PRVCICH
         CALL GDTA6S(TISK,IOP)
C ZMENA NAZVU ULOHY/UKONCENI/ZRUSENI IS
         CALL GDTA7S(TISK,IOP)
         IF(IOP.GE.0)  GOTO 0199
C OBNOVEN POCET OPERNYCH BODU
            POB = POMPOB
            RETURN
0199  CONTINUE
      GOTO 0102
C
      END
