C VOLNA SIT
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C
      SUBROUTINE GDTAVS(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      INTEGER  VYHYBK,I,J,IBOD,IER,IOUT
      INTEGER*1  BOD(14)
      DOUBLE PRECISION  CP(CPDIM)
      EQUIVALENCE  (CP,SBY)
      EXTERNAL  GDTTPN
461   FORMAT(/' 2. KROK  GSO')
47    FORMAT(/
     /' POSTUP RESENI DOKUMENTUJE NASLEDUJICI VYPIS NOREM,'/
     /' ZISKANYCH ALGORITMEM  GSO  PRI POSTUPNE ORTOGONALIZACI'/
     /' SLOUPCU VSTUPNI MATICE'//' POCET SLOUPCU:',I5)
11    FORMAT( ' JAKO OPERNE BYLY ZADANY VSECHNY URCOVANE BODY')
12    FORMAT( ' JAKO OPERNE BYLY ZADANY BODY S CISLY:')
13    FORMAT(/' DOKONCEN 2. KROK  GSO')
14    FORMAT(/' ULOHA NEMA JEDNOZNACNE RESENI')
C
      IF(DEFEKT.LE.0)  GOTO 10
      VYHYBK = 0
C ZADANI NAZVU VARIANTY A MNOZINY OPERNYCH BODU
1     CALL GDTAVZ(AW)
      IF(KK.EQ.2)  GOTO (10,20) VYHYBK+1
      CALL GDTTHL(GSGDPT,'LOKALIZACE VOLNE SITE:')
0103  IF(POB.NE.URCBOD)  GOTO 0104
         CALL GDSSTR(1,0)
         WRITE(GSGDPT,11)
         GOTO 0199
0104  CONTINUE
         CALL GDSSTR(1,2)
         WRITE(GSGDPT,12)
         CALL GDTBU1(.TRUE.,.FALSE.)
         I = 0
0202     I = I + 1
         IF(I.GT.SBPOC)  GOTO 0299
         IF(INTERT(I).NE.'O')  GOTO 0202
            CALL GDTEXT(I,BOD)
            IBOD = 14
            IF(BOD(13).EQ.' ')  IBOD = 13
            BOD(IBOD) = ','
            CALL GDTBUF(BOD,IBOD)
            GOTO 0202
0299     CONTINUE
         CALL GDTBU2(1)
0199  CONTINUE
      CALL GDSSTR(1,0)
      WRITE(GSGDPT,461)
      WRITE(ITT,   461)
      WRITE(ITT,47)  DEFEKT
      CALL GDTICZ('ZAPIS')
      CALL GDTTP0
C
      CALL MTGSO2(AW,VIRDIM,POCPOZ,POCNEZ,1,0,3,.TRUE.,6E-8,TOL,
     /            2*POB,DEFEKT,GDTTPN,IER,INDX,INDS,CP)
C
      CALL GDTICZ('CTENI')
0303  IF(IER.EQ.0)  GOTO 0399
         CALL GDSSTR(2,0)
         WRITE(GSGDPT,14)
         WRITE(ITT   ,14)
         CALL GDSDAN(
     /   '/A/BUDES DEFINOVAT NOVOU VARIANTU RESENI? (A/N): ',IOUT)
         IF(IOUT.EQ.2)  GOTO 20
         VYHYBK = 1
         GOTO 1
0399  CONTINUE
      CALL GDSSTR(2,0)
      WRITE(GSGDPT,13)
      WRITE(ITT   ,13)
C
10    KK = 1
      RETURN
20    KK = 2
      RETURN
C
      END
