C VYPIS PREHLEDU MERENYCH DELEK, ORIENTOVANYCH SMERU, ABS. CLENU A VAH
C=======================================================================
C         1. VERZE  /SRPEN 1984/         VUGTK
C
C AW    PRACOVNI POLE PRO UKLADANI MATICE SOUSTAVY ROVNIC OPRAV
C LUN   CISLO LOGICKE JEDNOTKY - TISK PREHLEDU
C ITYP  TYP HLAVICKY / TISKU
C       ITYP = 1 ... TISKNOU SE VSECHNY ULOZENE UDAJE
C       ITYP = 2 ... TISKNOU SE POUZE UDAJE S VYBOCUJICIMI ABS. CLENY
C
      SUBROUTINE GDTDS1(AW,LUN,ITYP)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      INTEGER  LUN,ITYP,CORB,I,IND,PIND,GDTSUM
      INTEGER*4 GDTIND
      LOGICAL  EOF,WAIT
      DOUBLE PRECISION  MERPRV
      REAL  ABSCL,ABSVAH
      INTEGER*1  SSS(13),CCC(13),ZNAK
      EXTERNAL  GDTA41
C
      IF(ITYP.EQ.1)  CALL GDTTHL(LUN,
     /'PREHLED MERENYCH DELEK, ORIENTOVANYCH SMERU, ABS. CLENU A VAH:')
      IF(ITYP.EQ.2)  CALL GDTTHL(LUN,'PREHLED VYBOCUJICICH ABS. CLENU:')
      CALL GDTA41(LUN)
C
C COROUTINE A - VYTVORENI POSLOUPNOSTI INDEXU IND PRVKU SEZNAMU SEZMER
      ASSIGN 20 TO CORB
      CALL GDTOS1
10    CALL GDTOSN(IND,I,EOF,EOF)
      IF(ITYP.NE.2)  GOTO 15
         IF(EOF)  GOTO 15
         IF(VAHA(IND).GE.0)  GOTO 10
15    CONTINUE
C  VOLANI COROUTINE B
      GOTO CORB
C
C COROUTINE B - TISK PREHLEDU MERENYCH PRVKU, ABS. CLENU A VAH
20    CONTINUE
      ASSIGN 25 TO CORB
      WAIT = LUN.EQ.ITT
1002  IF(EOF)  GOTO 1099
         IF(LUN.EQ.GSGDPT)  CALL GDTSTR(1,6,GDTA41)
         WRITE(LUN,2)
         CALL GDTEXT(CST(IND),SSS)
         PIND = CST(IND)
1102     IF(EOF.OR.PIND.NE.CST(IND))  GOTO 1199
            CALL GDTEXT(CCI(IND),CCC)
            IF(LUN.EQ.GSGDPT)  CALL GDTSTR(1,0,GDTA41)
            ZNAK = '*'
C*          IFR = 5
            MERPRV = PRVEK(IND)
1203        IF(TYPP(IND).NE.'S')  GOTO 1299
               MERPRV = (MERPRV + SBZ(CST(IND)))*RO
               CALL GDSGRA(MERPRV)
               ZNAK = ' '
C*             IFR = 6
1299        CONTINUE
            ABSCL  = AW(GDTIND(IND-GDTSUM(TYPP,IND,' '),NARED))
            ABSCL = ABSCL/ABS(VAHA(IND))
            ABSVAH = VAHA(IND)**2
C*          WRITE(LUN,2)  SSS,CCC,TYPP(IND),MERPRV,ABSCL,ZNAK,ABSVAH
C*2         FORMAT(1X,2(13A1,2X),A1,F14.<IFR>,F12.2,A1,E12.4)
            IF(TYPP(IND).EQ.'S') THEN
               WRITE(LUN,2)  SSS,CCC,TYPP(IND),MERPRV,ABSCL,ZNAK,ABSVAH
2              FORMAT(1X,2(13A1,2X),A1,F14.6,F12.2,A1,E12.4)
            ELSE
               WRITE(LUN,3)  SSS,CCC,TYPP(IND),MERPRV,ABSCL,ZNAK,ABSVAH
3              FORMAT(1X,2(13A1,2X),A1,F14.5,F12.2,A1,E12.4)
            END IF
C*          CALL PPINI1(' ',13,SSS)
            DO 9981 II81=1,13
9981           SSS(II81) = ' '	
C  VOLANI COROUTINE A
            GOTO 10
25          CONTINUE
            GOTO 1102
1199     CONTINUE
         IF(LUN.EQ.ITT)  CALL GDTPAU(WAIT)
         GOTO 1002
1099  CONTINUE
      RETURN
C
      END
