C DEFINICE SITE
C=======================================================================
C         1. VERZE      /CERVEN 1984/           VUGTK
C       * 5. VERZE      /ZARI 1989/             VUGTK      ALES CEPEK
C
C KK = 1  NASLEDUJE ZPRACOVANI PODLE SS
C KK = 2  UKONCENI PROGRAMU
C
      SUBROUTINE GDTDFS
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  IOUT,II,GDTSUM
      INTEGER*1  BOD(15)
      DATA  BOD /' ',14*','/
    1 FORMAT(' PREHLED ZADANYCH BODU'/)
    2 FORMAT(/
     /' POCET ZADANYCH PEVNYCH BODU   :',I5/
     /' POCET ZADANYCH URCOVANYCH BODU:',I5)
    3 FORMAT('0SIT NENI DEFINOVANA')
    4 FORMAT('0UPOZORNENI: VSECHNY BODY JSOU PEVNE')
    5 FORMAT('0UPOZORNENI: POCET PEVNYCH BODU NESTACI K JEDNOZNACNE',
     /' LOKALIZACI SITE'/'             V SOUR. SOUSTAVE',
     /' (VOLNA SIT)')
C
0102  CONTINUE
      CALL TTZAHL(ITT,'DEFINICE SITE:')
      CALL GDSSTR(2,17)
      CALL GDTTHL(GSGDPT,'DEFINICE SITE:')
      WRITE(GSGDPT,1)
      CALL GDTZCP(-1,0)
0152  CONTINUE
      CALL GDTZCB('CISLO PEVNEHO BODU: ',   'P',.TRUE.)
      CALL GDTZCB('CISLO URCOVANEHO BODU: ','U',.TRUE.)
      PEVBOD = GDTSUM(TYPB,SBPOC,'P')
      URCBOD = GDTSUM(TYPB,SBPOC,'U')
      POCBOD = PEVBOD + URCBOD
      WRITE(ITT,2)  PEVBOD,URCBOD
0503  IF(PEVBOD.LE.0)  GOTO 0599
      CALL GDTBU1(.FALSE.,.TRUE.)
C*    CALL GDTBUF('PEVNE BODY:',0)
      CALL GDTBUF('PEVNE BODY:',11)
      DO 0553 II=1,SBPOC
      IF(TYPB(II).NE.'P')  GOTO 0553
      CALL GDTEXT(II,BOD(2))
      CALL GDTBUF(BOD,15)
0553  CONTINUE
      CALL GDTBU2(1)
0599  CONTINUE
0603  IF(URCBOD.LE.0)  GOTO 0699
      CALL GDTBU1(.FALSE.,.TRUE.)
C*    CALL GDTBUF('URCOVANE BODY:',0)
      CALL GDTBUF('URCOVANE BODY:',14)
      DO 0653 II=1,SBPOC
      IF(TYPB(II).NE.'U')  GOTO 0653
      CALL GDTEXT(II,BOD(2))
      CALL GDTBUF(BOD,15)
0653  CONTINUE
      CALL GDTBU2(1)
0699  CONTINUE
      CALL GDSDAN('/N/CHCES DOPLNIT DALSI BODY? (A/N): ',IOUT)
      IF(IOUT.EQ.1)  GOTO 0152
      CALL GDSSTR(3,0)
      WRITE(GSGDPT,2)  PEVBOD, URCBOD
      IF(POCBOD.GT.0)  GOTO 0199
      CALL GDSSTR(2,0)
      WRITE(GSGDPT,3)
      WRITE(ITT   ,3)
      CALL GDSDAN('/A/MAM UKONCIT VYPOCET? (A/N): ',IOUT)
0303  IF(IOUT.NE.1)  GOTO 0399
         KK = 2
         RETURN
0399  CONTINUE
      GOTO 0152
0199  CONTINUE
0403  IF(URCBOD.GT.0)  GOTO 0404
         CALL GDSSTR(2,0)
         WRITE(GSGDPT,4)
         WRITE(ITT   ,4)
         GOTO 0499
0404  IF(PEVBOD.GE.2)  GOTO 0499
         CALL GDSSTR(3,0)
         WRITE(GSGDPT,5)
         WRITE(ITT   ,5)
0499  CONTINUE
      SS = 1
      KK = 1
      RETURN
C
      END
