C TISK PREHLEDU MER. DELEK, ORIENTOVANYCH SMERU, ABS. CLENU A VAH
C======================================================================
C         1. VERZE  /SRPEN 1984/         VUGTK
C
      SUBROUTINE GDTDSA(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      INTEGER  PPBIT1,IOUT
C
0103  IF(PPBIT1(PK,3).EQ.0)  GOTO 0104
      CALL GDSDAN('/A/POZADUJES TISK PREHLEDU VSECH ABS. CLENU'//
     /' A VAH DO PROTOKOLU? (A/N): ',IOUT)
      IF(IOUT.EQ.2)  GOTO 9999
      GOTO 0199
0104  CONTINUE
      IF(PPBIT1(PK,5).NE.0)  GOTO 9999
0199  CONTINUE
      CALL GDTDS1(AW,GSGDPT,1)
9999  CONTINUE
      RETURN
C
      END
