C DEFINICE A ULOZENI POSTUPOVEHO KLICE A SYSTEMOVYCH PARAMETRU
C=======================================================================
C         1. VERZE      /SRPEN 1984/            VUGTK
C       * 5. VERZE      /DUBEN 1990/            VUGTK      ALES CEPEK
C
      SUBROUTINE GDTDSP
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  PPBIT1,IOUT
      LOGICAL  IMPL,ZPET
      REAL  M0SIT
C
C ULOZENA  M0  PRO PRIPAD  SS=>4
      M0SIT = M0
C NASTAVENI IMPLICITNICH HODNOT BITU POSTUPOVEHO KLICE
C*    PK = 0
C*    CALL PPBIS1(PK,0,1,2,3)
C*    CALL GDSPKL(ITT,PK,1,IOUT)
1000  CONTINUE
      IMPK = 0
      CALL PPBIS1(IMPK,0)
      CALL PPBIS1(IMPK,1)
      CALL PPBIS1(IMPK,2)
      CALL PPBIS1(IMPK,3)
      CALL GDSPKL(ITT,GSGDVV,'GETU03',IMPK,PK,1,IOUT)
      KK = 2
      IF(IOUT.EQ.-2)  RETURN
      KK = 1
      GOTO (3333,4000,3000) IOUT
C
C DIALOG PRO TVORBU POSTUPOVEHO KLICE (PPBIT1(PK,n).EQ.0 <===> Ano)
3000  CONTINUE
      CALL TTZAHL(ITT,'VYTVORENI POSTUPOVEHO KLICE:')
C*    PK = 0
3001  CALL GDSBPK(PK,1,ZPET,'ZKRACENA FORMA PROTOKOLU? (A/N): ',0)
      IF(ZPET)  GOTO 1000
C*    CALL GDTPBS(0,IOUT)
3002  CALL GDSBPK(PK,1,ZPET,
     /'BUDE VYBER ZAMER RIZEN OPERATOREM? (A/N): ',1)
      IF(ZPET)  GOTO 3000
C*    CALL GDTPBS(1,IOUT)
3003  CALL GDSBPK(PK,1,ZPET,
     /'BUDE DANA MOZNOST VOLIT SYST. PARAMETRY? (A/N): ',2)
      IF(ZPET)  GOTO 3002
C*    CALL GDTPBS(2,IOUT)
3004  CALL GDSBPK(PK,1,ZPET,
     /'BUDE DIALOG VEDEN STRUCNOU FORMOU? (A/N): ',3)
      IF(ZPET)  GOTO 3003
C*    CALL GDTPBS(3,IOUT)
3005  CONTINUE
      IF(PPBIT1(PK,3).NE.0)  GOTO 3006
      CALL GDSBPK(PK,1,ZPET,
     /'MAJI BYT NA OBRAZOVKU VYPISOVANY I DETAILNI PREHLEDY'//
     /' VYSLEDKU? (A/N): ',4)
      IF(ZPET)  GOTO 3004
C*    CALL GDTPBS(4,IOUT)
3006  CONTINUE
      IF(PPBIT1(PK,3).NE.0)  GOTO 3007
      CALL GDSBPK(PK,1,ZPET,
     /'MAJI BYT DETAILNI PREHLEDY TISTENY DO PROTOKOLU? (A/N): ',5)
      IF(ZPET)  GOTO 3005
C*    CALL GDTPBS(5,IOUT)
C*    CALL GDTPBS(6,IOUT)
C*    IF(IOUT.EQ.2)  GOTO 4000
      IF(PPBIT1(PK,5).EQ.0) THEN
         CALL PPBIC1(PK,6)
      ELSE
         CALL PPBIS1(PK,6)
         GOTO 3999
      END IF
3007  CALL GDSBPK(PK,1,ZPET,
     /'MAJI BYT VSECHNY TABELARNI PREHLEDY OZNACENY V PROTOKOLU'//
     /' NAZVEM ULOHY? (A/N): ',6)
      IF(PPBIT1(PK,3).EQ.0.AND.ZPET)  GOTO 3006
      IF(PPBIT1(PK,3).NE.0.AND.ZPET)  GOTO 3004
C*    CALL GDTPBS(6,IOUT)
3999  CONTINUE
C
3333  CALL GDSZPK(ITT,GSGDVV,'GETU03',PK,1)
C
4000  CONTINUE
      IMPL = PPBIT1(PK,2).NE.0
      IF(.NOT.IMPL)  CALL TTZAHL(ITT,'VOLBA SYSTEMOVYCH PARAMETRU:')
4001  M0 = 1E1
      IF(SS.GE.4)  M0 = M0SIT
      IF(SS.GE.4)  GOTO 4002
      IF(IMPL)  GOTO 4002
      CALL TTASKR(ITT,
     /'APRIORNI JEDNOTKOVA STREDNI CHYBA M0 [IMPL. 10 MM/CC]: ',
     /IOUT,M0,1)
      IF(M0.LE.0)  GOTO 4001
      IF(IOUT.GE.0)  GOTO 4002
      IF(IOUT.EQ.-2) GOTO 1000
      GOTO 4001
4002  TOLABS = 1E3
      IF(IMPL)  GOTO 4003
      CALL TTPUT1(ITT,0,
     /'TOLERANCE PRO TESTOVANI ABSOLUTNICH CLENU ROVNIC OPRAV:')
      CALL TTASKR(ITT,
     /'- ROZDIL DELEK, RESP. PRICNA ODCHYLKA [IMPL. 1000 MM]: ',
     /IOUT,TOLABS,1)
      IF(TOLABS.LE.0)  GOTO 4002
      IF(IOUT.GE.0)  GOTO 4003
      IF(IOUT.EQ.-2) GOTO 4001
      GOTO 4002
4003  TOL = 1E-2
      IF(IMPL)  GOTO 4004
      CALL TTPUT1(ITT,0,
     /'TOLERANCE PRO IDENTIFIKACI LINEARNE ZAVISLYCH SLOUPCU:')
      CALL TTASKR(ITT,
     /'V ORTOGONALIZOVANYCH MATICICH [IMPL. 0.01]: ',IOUT,TOL,1)
      IF(TOL.LE.0)  GOTO 4003
      IF(IOUT.GE.0)  GOTO 4004
      IF(IOUT.EQ.-2) GOTO 4002
      GOTO 4003
4004  CONTINUE
      RETURN
C
      END
