C VYPIS PREHLEDU STR. CHYB A PARAMETRU ELIPS CHYB
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C
      SUBROUTINE GDTELI(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
C
C POZADAVKY NA VYPIS
      CALL GDTPNV
      IF(KK.EQ.2)  RETURN
C VYPOCET KOEF. ZVETSENI KONFID. ELIPSY
      CALL GDTPR4
C VLASTNI VYPIS
      CALL GDTVY2(AW)
C
      END
