C PREVOD PRACOVNIHO CISLA BODU (SEZBOD) NA EXTERNI TVAR (GEODET)
C=======================================================================
C         1. VERZE  /SRPEN 1984/         VUGTK
C
C INDEX  UMISTENI BODU V SEZNAMU SEZBOD
C ZVCB   ZNAKOVE VYJADRENI CISLA BODU (DOPLNENY MEZERY ZLEVA)
C
      SUBROUTINE GDTEXT(INDEX,ZVCB)
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  INDEX,CB(3),II
      INTEGER*1  ZVCB(13)
C
      CB(1) = CB1(INDEX)
      CB(2) = CB2(INDEX)
      CB(3) = CB3(INDEX)
      CALL GDSKCB(3,ZVCB,II,CB,II)
      RETURN
C
      END
