C PROCEDURA TRANSFORMUJE CISLO BODU V INTERNIM TVARU NA PRACOVNI
C CISLO BODU, KTERE UDAVA INDEX V SEZNAMU BODU
C=======================================================================
C         1. VERZE  /CERVEN 1984/         VUGTK
C
C INTCB  VSTUPNI PARAMETR, CISLO BODU V INTERNIM TVARU
C IPCB   VYSTUPNI PARAMETR, PRACOVNI CISLO BODU
C DOPLN  VSTUPNI PARAMETR, LOGICKA PROMENNA, KTERA POVOLUJE DOPLNENI
C        NOVEHO BODU DO SEZNAMU BODU
C NOVY   VYSTUPNI PARAMETR, LOGICKA PROMENNA UDAVA, ZE BOD NEBYL
C        NALEZEN V SEZNAMU BODU (JE-LI HODNOTA PARAMETRU DOPLN=.TRUE.,
C        JE NOVY BOD DO SEZNAMU DOPLNEN, JE-LI HODNOTA PARAMETRU
C        DOPLN=.FALSE., BOD DO SEZNAMU BODU NENI DOPLNEN A HODNOTA
C        PARAMETRU IPCB NENI DEFINOVANA)
C
      SUBROUTINE GDTHCB(INTCB,IPCB,DOPLN,NOVY)
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  INTCB(3),IPCB,II
      LOGICAL  DOPLN,NOVY
C
      II = SBPOC + 1
      CB1(II) = INTCB(1)
      CB2(II) = INTCB(2)
      CB3(II) = INTCB(3)
      II = 0
0102  II = II + 1
      IF(CB3(II).NE.INTCB(3))  GOTO 0102
      IF(CB2(II).NE.INTCB(2))  GOTO 0102
      IF(CB1(II).NE.INTCB(1))  GOTO 0102
      NOVY = II.GT.SBPOC
      IF(NOVY.AND.DOPLN)  SBPOC = II
      NOVY = NOVY.OR.TYPB(II).EQ.' '
      IPCB = II
      RETURN
C
      END
