C PROCEDURA TRANSFORMUJE INDEX PRVKU/NEZNAME NA ODPOVIDAJICI CISLO
C RADKU V MATICI SOUSTAVY ROVNIC OPRAV
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C
      SUBROUTINE GDTIAW(TYP,INDEX,IAW)
C
$INCLUDE: 'GDTSOW.COM'
C
C TYP    'P' MERENY PRVEK/'Z','Y','X' NEMERENA NEZNAMA
C INDEX  INDEX PRVKU V SEZMER RESP. NEZNAME V SEZBOD
C IAW    CISLO RADKU ODPOVIDAJICI DANEMU PRVKU NEBO NEZNAME
C        (JE-LI TYP PRVKU NEBO NEZNAME ' ', JE IAW = 0 )
C
      INTEGER*1  TYP
      INTEGER  INDEX,IAW,GDTSUM,I
C
      IAW = 0
0103  IF(TYP.NE.'P')  GOTO 0104
         IF(TYPP(INDEX).EQ.' ')  RETURN
         IAW = INDEX - GDTSUM(TYPP,INDEX,' ')
         GOTO 0199
0104  IF(TYPB(INDEX).NE.' ')  GOTO 0105
         GOTO 0199
0105  IF(TYP.NE.'Z')  GOTO 0106
         IF(SBZ(INDEX).LT.0D0)  RETURN
         IAW = POCPOZ
         DO 01051 I=1,INDEX
            IF(TYPB(I).EQ.' ')  GOTO 01051
            IF(SBZ(I).GE.0D0)  IAW = IAW + 1
01051     CONTINUE
         GOTO 0199
0106  CONTINUE
         IAW = POCPOZ + POCORP + 2*GDTSUM(TYPB,INDEX,'U')
         IF(TYP.EQ.'Y')  IAW = IAW - 1
0199  CONTINUE
C
      END
