C INICIALIZACE / CTENI / ZAPIS  STAVOVE OBLASTI COMMON /GDTSOW/
C=======================================================================
C         1. VERZE  /CERVEN 1984/         VUGTK
C       * 5. VERZE      /ZARI 1989/             VUGTK      ALES CEPEK
C
      SUBROUTINE GDTICZ(KOD)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  KOD,KOD1,KOD2,KOD3
      INTEGER  II,I,J,F1,F2
      LOGICAL  LSAVE1
C*    F1() = (I-1)*ISREC + 1
C*    F2() = MIN0(I*ISREC,SOWDIM)
      F1(II) = (II-1)*ISREC + 1
      F2(II) = MIN0(II*ISREC,SOWDIM)
C PRIPUSTNE HODNOTY VSTUPNIHO PARAMETRU: INICIALIZACE / CTENI / ZAPIS
      DATA  KOD1 /'INIC'/  KOD2 /'CTEN'/  KOD3 /'ZAPI'/
C
0103  IF(KOD.NE.KOD1)  GOTO 0104
         LSAVE1 = PRASDZ
         DO 0299 I=1,SOWDIM
0299     SOW(I) = 0
         PRASIS = .TRUE.
         PRASDZ = LSAVE1
C*       CALL IDATE(DVYT(2),DVYT(1),DVYT(3))
         CALL GETDAT(DVYT(3),DVYT(2),DVYT(1))
         ISEZ = ISEZT
         CALL PPMOV1(1,SOUBT,1,SOUB,1,40)
         GOTO 0199
0104  IF(KOD.NE.KOD2)  GOTO 0105
         DO 0399 I=1,SOWREC
0399     READ (GSGDIS,REC=I)  (SOW(J),J=F1(I),F2(I))
         PRASIS = .TRUE.
         GOTO 0199
0105  IF(KOD.NE.KOD3.OR..NOT.PRASIS)  GOTO 0199
C*       CALL IDATE(DUZA(2),DUZA(1),DUZA(3))
         CALL GETDAT(DUZA(3),DUZA(2),DUZA(1))
         DO 0499 I=1,SOWREC
0499     WRITE(GSGDIS,REC=I)  (SOW(J),J=F1(I),F2(I))
         PRASIS = .FALSE.
0199  CONTINUE
      RETURN
C
      END
