C INKREMENTOVANI PRACOVNIHO CITACE RADKU ZAPSANYCH NA OBRAZOVKU
C (VOLANI FUNKCE MUSI NASLEDOVAT VZDY AZ PO PROVEDENI ZAPISU)
C=======================================================================
C         1. VERZE  /ZARI 1984/
C
      LOGICAL FUNCTION GDTINC(CITAC)
C
      INTEGER  CITAC,MAXCIT
      SAVE  MAXCIT
C
0103  IF(CITAC.GE.0)  GOTO 0104
         MAXCIT = -CITAC
         GDTINC = .TRUE.
         GOTO 0199
0104  CONTINUE
         IF(CITAC.EQ.0)  CITAC = 1
         CITAC = CITAC + 1
0203     IF(CITAC.LE.MAXCIT)  GOTO 0204
            CITAC  = 1
            GDTINC = .TRUE.
            GOTO 0299
0204     CONTINUE
            GDTINC = .FALSE.
0299     CONTINUE
0199  CONTINUE
C
      END
