C VYPOCET KOEFICIENTU A ABSOLUTNIHO CLENU
C=======================================================================
C         1. VERZE  /SRPEN 1984/         VUGTK
C
C INDEX  UMISTENI MERENEHO PRVKU V SEZNAMU SEZMER
C ZST    KOEFICIENT ... ORIENTACNI POSUN
C YST    KOEFICIENT ... SOURADNICE Y (STANOVISKO)
C XST    KOEFICIENT ... SOURADNICE X (STANOVISKO)
C ACL    ABSOLUTNI CLEN
C IND    INDEXY SLOUPCU V MATICI ROVNIC OPRAV
C        IND(1)  ORIENTACNI POSUN (STANOVISKO)
C        IND(2)  SOURADNICE Y     (STANOVISKO)
C        IND(3)  SOURADNICE X     (STANOVISKO)
C        IND(4)  SOURADNICE Y     (CIL)
C        IND(5)  SOURADNICE X     (CIL)
C        NENI-LI HODNOTA INDEXU SLOUPCE DEFINOVANA, PREDAVA SE
C        FIKTIVNI HODNOTA NARED
C IER    INDIKACE VYSLEDKU (IER=0 USPESNY VYPOCET/IER=1 TOTOZNE BODY)
C
      SUBROUTINE GDTKOE(INDEX,ZST,YST,XST,ACL,IND,IER)
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  INDEX,IER,I,J,IND(5),GDTSUM
      REAL  ZST,YST,XST,ACL
      DOUBLE PRECISION  Y(2),X(2),SM,D,ODM,LD,K,POM
      DOUBLE PRECISION  PSIN,PCOS
      J = CST(INDEX)
      Y(1) = SBY(J)
      X(1) = SBX(J)
      J = CCI(INDEX)
      Y(2) = SBY(J)
      X(2) = SBX(J)
      CALL NGSMDA(Y,X,SM,D,IER)
      IF(IER.NE.0) RETURN
      PSIN = DSIN(SM)
      PCOS = DCOS(SM)
      IF(DABS(PSIN).LT.1D-12)  PSIN = 0D0
      IF(DABS(PCOS).LT.1D-12)  PCOS = 0D0
      ODM = ABS(VAHA(INDEX))
      K = 1D1*RO
0103  IF(TYPP(INDEX).NE.'S')  GOTO 0104
         ZST = -ODM
         POM =(K/D)*ODM
         YST = -POM*PCOS
         XST =  POM*PSIN
         LD = SM-PRVEK(INDEX)-SBZ(CST(INDEX))
801      IF(DABS(LD).LT.3.2D0)  GOTO 802
         LD = LD-DSIGN(DVEPI,LD)
         GOTO 801
802      ACL = LD*RO*1D4
         IF(ABS(ACL)/(K/D).LE.TOLABS)  GOTO 803
         POCVAC = POCVAC + 1
         VAHA(INDEX) = -VAHA(INDEX)
803      ACL = ACL*ODM
         GOTO 0199
0104  IF(TYPP(INDEX).NE.'D')  GOTO 0199
         ZST = 0E0
         YST = -ODM*PSIN
         XST = -ODM*PCOS
         ACL = (D-PRVEK(INDEX))*1D3
         IF(ABS(ACL).LE.TOLABS)  GOTO 804
         POCVAC = POCVAC + 1
         VAHA(INDEX) = -VAHA(INDEX)
804      ACL = ACL*ODM
0199  CONTINUE
C*    CALL PPINI2(NARED,5,IND)
      DO 9981 II81=1,5
9981      IND(II81) = NARED
      J = CST(INDEX)
0203  IF(SBZ(J).LT.0D0)  GOTO 0299
         IND(1) = 0
         DO 805 I=1,J
805      IF(SBZ(I).GE.0D0)  IND(1) = IND(1) + 1
0299  CONTINUE
0304  IF(TYPB(J).NE.'U')  GOTO 0399
         IND(2) = POCORP + 2*GDTSUM(TYPB,J,'U') - 1
         IND(3) = IND(2) + 1
0399  CONTINUE
      J = CCI(INDEX)
0403  IF(TYPB(J).NE.'U')  GOTO 0499
         IND(4) = POCORP + 2*GDTSUM(TYPB,J,'U') - 1
         IND(5) = IND(4) + 1
0499  CONTINUE
      RETURN
C
      END
