C TEST CHYBY Z LINEARIZACE
C=======================================================================
C         1. VERZE      /RIJEN 1984/            VUGTK
C       * 5. VERZE      /ZARI 1989/             VUGTK      ALES CEPEK
C
      SUBROUTINE GDTLIN(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      INTEGER  INDEX,IPOZ,IOPR,IPOC,IPOS
      REAL  MAXDIF,DIF
      LOGICAL  NOVOSN,EOF,WAIT
      INTEGER*1  TEXTD(71),TEXT(72),S(13),C(13)
      EQUIVALENCE  (TEXTD,TEXT)
      CHARACTER    CTEXTD*71, CTEXT*72
      EQUIVALENCE (CTEXTD,CTEXT,TEXTD)
      EXTERNAL  GDT114
      CHARACTER*(*) RET
      PARAMETER  (RET='TEST CHYBY Z LINEARIZACE:')
111   FORMAT(' BYLY URCENY ROZDILY MEZI  DELKAMI/SMERNIKY  VYPOCTEM',
     /' JEDNAK ZE SOURAD-'/' NIC, JEDNAK Z ROVNIC OPRAV; MAX.',
     /' ROZPOR: ',29A1/1X,70A1)
1111  FORMAT(
     /'DIFERENCE V DELCE',F9.3,' MMPRO DELKU   ',13A1,' --> ',13A1)
1112  FORMAT(
     /'PRICNA ODCHYLKA  ',F9.3,' MMPRO SMERNIK ',13A1,' --> ',13A1)
115   FORMAT(71A1)
C
      INDEX  = 1
      MAXDIF = 0E0
      CALL GDTOS1
0102  CALL GDTOSN(IPOZ,IOPR,NOVOSN,EOF)
      IF(EOF)  GOTO 0199
         CALL GDTDIF(AW,IPOZ,IOPR,DIF,TEXTD,NOVOSN,IPOC)
0203     IF(ABS(MAXDIF).GE.ABS(DIF))  GOTO 0299
            INDEX  = IPOZ
            MAXDIF = DIF
0299     CONTINUE
         GOTO 0102
0199  CONTINUE
      CALL GDTEXT(CST(INDEX),S)
      CALL GDTEXT(CCI(INDEX),C)
C*    IF(TYPP(INDEX).EQ.'D')  ENCODE(72,1111,TEXT)  MAXDIF,S,C
C*    IF(TYPP(INDEX).EQ.'S')  ENCODE(72,1112,TEXT)  MAXDIF,S,C
      IF(TYPP(INDEX).EQ.'D')  WRITE(CTEXT,1111)     MAXDIF,S,C
      IF(TYPP(INDEX).EQ.'S')  WRITE(CTEXT,1112)     MAXDIF,S,C
      CALL GDSMEZ(TEXT(30),43,IPOC)
      CALL GDTTHL(GSGDPT,RET)
      CALL GDTTHL(ITT   ,RET)
      CALL GDSSTR(3,0)
      WRITE(GSGDPT,111)  TEXT
      WRITE(ITT   ,111)  TEXT
      CALL GDTPNV
      IF(KK.EQ.2)  RETURN
0303  IF(.NOT.LPT)  GOTO 0399
         CALL GDSSTR(0,0)
         CALL GDTTHL(GSGDPT,RET)
         CALL GDT114(GSGDPT)
0399  CONTINUE
0403  IF(.NOT.LTT)  GOTO 0499
         CALL GDTTHL(ITT,RET)
         WAIT = .TRUE.
C CITAC ZPRACOVANYCH OSNOV
         IPOC = 0
0499  CONTINUE
      CALL GDTOS1
0502  CALL GDTOSN(IPOZ,IOPR,NOVOSN,EOF)
      IF(EOF)  GOTO 0599
0603     IF(.NOT.NOVOSN)  GOTO 0699
0803        IF(.NOT.LTT)  GOTO 0899
               IPOC = IPOC + 1
               IF(IPOC.NE.1)  CALL GDTPAU(WAIT)
               IF(WAIT)  CALL GDT114(ITT)
0899        CONTINUE
0699     CONTINUE
         CALL GDTDIF(AW,IPOZ,IOPR,DIF,TEXTD,NOVOSN,IPOS)
0903     IF(.NOT.LPT)  GOTO 0999
            CALL GDTSTR(IPOS,0,GDT114)
            WRITE(GSGDPT,115)  TEXTD
0999     CONTINUE
1003     IF(.NOT.LTT)  GOTO 1099
            WRITE(ITT   ,115)  TEXTD
1099     CONTINUE
         GOTO 0502
0599  CONTINUE
      IF(LTT)  CALL GDTPAU(WAIT)
C
      END
