C OPAKOVANE VYROVNANI
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C
      SUBROUTINE GDTOPV(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      INTEGER  IOUT,I
      INTEGER*1  TYP
1     FORMAT(/' POKUD SE BUDE PRACOVAT S OPERNYMI BODY, JEJICHZ',
     /' DANE SOURADNICE NEMAJI'/' BYT NAHRAZENY VYROVNANYMI,',
     /' JE TREBA NEJPRVE PRIKROCIT K VARIANTNIMU'/' ZPRACOVANI',
     /' VOLNE SITE (ZADAT OPERNE BODY).'/)
109   FORMAT('0STAVAJICI (PRIBLIZNE) SOURADNICE VSECH URCOVANYCH BODU')
1091  FORMAT(' BYLY NAHRAZENY VYROVNANYMI')
1092  FORMAT(' (VCETNE OPERNYCH) BYLY NAHRAZENY VYROVNANYMI')
1093  FORMAT(' (KROME OPERNYCH) BYLY NAHRAZENY VYROVNANYMI')
110   FORMAT('0STAVAJICI (PRIBLIZNE) ORIENT. POSUNY BYLY NAHRAZENY',
     /' VYROVNANYMI')
1101  FORMAT(/
     /' OPAKOVANE VYROVNANI'/
     /' *******************')
C
      IF(DEFEKT.LE.0)  GOTO 200
      IF(POB.GT.0)  GOTO 100
      WRITE(ITT,1)
      CALL GDSDAN(
     /'/A/PRIPOUSTIS ZMENU  V S E C H  URCOVANYCH BODU? (A/N): ',IOUT)
      IF(IOUT.EQ.1)  GOTO 200
      KK = 2
      RETURN
100   CALL GDSDAN(
     /'/A/MAJI BYT KORIGOVANY I SOURADNICE OPERNYCH BODU? (A/N): ',IOUT)
      IF(IOUT.EQ.1)  GOTO 200
      CALL GDTOPW(AW,.FALSE.,INTERT)
      CALL GDSSTR(3,0)
      WRITE(GSGDPT,109)
      WRITE(GSGDPT,1093)
      WRITE(ITT   ,109)
      WRITE(ITT   ,1093)
      GOTO 300
C
200   CONTINUE
      CALL GDTOPW(AW,.FALSE.,TYPB)
      CALL GDSSTR(3,0)
      WRITE(GSGDPT,109)
      WRITE(ITT   ,109)
2103  IF(POB.LE.0)  GOTO 2104
      WRITE(GSGDPT,1092)
      WRITE(ITT   ,1092)
      GOTO 2199
2104  CONTINUE
      WRITE(GSGDPT,1091)
      WRITE(ITT   ,1091)
2199  CONTINUE
C
300   CONTINUE
      IF(POCORP.LE.0)  GOTO 400
      CALL GDSDAN('/A/MAJI BYT KORIGOVANY I PRIBLIZNE HODNOTY'//
     /' ORIENTACNICH POSUNU? (A/N): ',IOUT)
      IF(IOUT.EQ.2)  GOTO 400
      CALL GDTOPW(AW,.TRUE.,TYPB)
      CALL GDSSTR(2,0)
      WRITE(GSGDPT,110)
      WRITE(ITT   ,110)
400   SS = 3
      KK = 1
      CALL GDSSTR(0,3)
      WRITE(GSGDPT,1101)
C*    CALL PPINI1(' ',25,NAZVAR)
      DO 9981 II81=1,25
9981      NAZVAR(II81) = ' '
      RETURN
C
      END
