C VYTVORENI POSLOUPNOSTI INDEXU PRVKU ULOZENYCH V SEZNAMU SEZMER.
C INDEXY PRVKU JSOU VYTVARENY PO OSNOVACH , V RAMCI OSNOV V PORADI
C V JAKEM JSOU PRVKY ULOZENY V SEZMER. PORADI OSNOV ODPOVIDA PORADI
C ULOZENI BODU V SEZNAMU SEZBOD.
C=======================================================================
C         1. VERZE  /ZARI 1984/         VUGTK
C
C IPOZ    INDEX MERENEHO PRVKU V SEZNAMU SEZMER
C IOPR    INDEX OPRAVY V MATICI SOUSTAVY ROVNIC OPRAV ODPOVIDAJICI
C         MERENEMU PRVKU ULOZENEMU NA POZICI IPOZ
C NOVOSN  PRVNI MERENY PRVEK OSNOVY (ZACATEK NOVE OSNOVY)
C EOF     NABYVA HODNOTY .TRUE. PO VYCERPANI SEZNAMU MERENYCH PRVKU
C
C PRED PRVNIM VOLANIM PROCEDURY GDTOSN MUSI BYT NASTAVENY HODNOTY
C INTERNICH PROMENNYCH PRIKAZEM:      CALL GDTOS1
C
      SUBROUTINE GDTOSN(IPOZ,IOPR,NOVOSN,EOF)
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  IPOZ,IOPR,QS,I,IND,INO
      LOGICAL  NOVOSN,EOF
C STAVOVY VEKTOR PROCEDURY
      SAVE  QS,I,IND,INO
C
      GOTO (1,2,3)  QS
C SMERNIK V SEZNAMU BODU - SEZBOD
1     I = 1
0102  IF(I.GT.SBPOC)  GOTO 0199
C CITAC MERENYCH PRVKU - INDEX OPRAVY BEZNEHO PRVKU
         INO = 0
C SMERNIK V SEZNAMU MERENYCH PRVKU - SEZMER
         IND = 1
         NOVOSN = .TRUE.
0202     IF(IND.GT.SMPOC)  GOTO 0299
0303        IF(TYPP(IND).EQ.' ')  GOTO 0399
               INO = INO + 1
               IF(CST(IND).NE.I)  GOTO 0399
               IPOZ   = IND
               IOPR   = INO
               EOF    = .FALSE.
               QS = 2
               RETURN
2              CONTINUE
               NOVOSN = .FALSE.
               INP = IND
0399        CONTINUE
            IND = IND + 1
            GOTO 0202
0299     CONTINUE
         I = I + 1
         GOTO 0102
0199  CONTINUE
3     EOF = .TRUE.
      QS = 3
      RETURN
C
      ENTRY GDTOS1
C INICIALIZACE STAVOVE PROMENNE
      QS = 1
      RETURN
C
      END
