C POMOCNA PROCEDURA PRO ZPRESNENI NEZNAMYCH
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C
      SUBROUTINE GDTOPW(AW,ZNEZN,TYPBOD)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
C ZPRESNENI ORIENTACNICH POSUNU  (NABO SOURADNIC)
      LOGICAL  ZNEZN
C BUDOU ZPRESNENY BODY PRO KTERE TYPBOD(I).EQ.'U'
      INTEGER*1  TYPBOD(1)
      INTEGER  IBOD,ISLPC,MAXSLP,IPOM
      INTEGER*4 GDTIND
      INTEGER*1  TYP
C
0103  IF(.NOT.ZNEZN)  GOTO 0104
         ISLPC = 1
         MAXSLP = POCORP
         GOTO 0199
0104  CONTINUE
         ISLPC  = POCORP + 1
         MAXSLP = NARED - 1
0199  CONTINUE
0202  IF(ISLPC.GT.MAXSLP)  GOTO 0299
         CALL GDTSTB(ISLPC,IBOD,TYP)
0303     IF(.NOT.ZNEZN)  GOTO 0304
            SBZ(IBOD) = SBZ(IBOD) +
     /      AW(GDTIND(POCPOZ+ISLPC,NARED))/(1D4*RO)
            CALL GDSRAD(SBZ(IBOD))
            ISLPC = ISLPC + 1
            GOTO 0399
0304     CONTINUE
0403        IF(TYPBOD(IBOD).NE.'U')  GOTO 0499
               IPOM = POCPOZ + ISLPC
               SBY(IBOD) = SBY(IBOD) + AW(GDTIND(IPOM  ,NARED))*1E-3
               SBX(IBOD) = SBX(IBOD) + AW(GDTIND(IPOM+1,NARED))*1E-3
0499        CONTINUE
            ISLPC = ISLPC + 2
0399     CONTINUE
         GOTO 0202
0299  CONTINUE
      RETURN
C
      END
