C STANOVENI POZADAVKU NA VYPIS
C=======================================================================
C         1. VERZE  /ZARI 1984/         VUGTK
C
      SUBROUTINE GDTPNV
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  PPBIT1,IOUT
C NEPOZADUJE SE ZADNY VYPIS
      KK = 2
0103  IF(PPBIT1(PK,3).NE.0)  GOTO 0104
      LPT = PPBIT1(PK,5).EQ.0
      LTT = PPBIT1(PK,4).EQ.0
      GOTO 0199
0104  CONTINUE
0202  CALL GDTPPK('/A/POZADUJES VYPIS PREHLEDU NA OBRAZOVKU? (A/N): ',
     /IOUT)
      IF(IOUT.EQ.-2)  RETURN
      LTT = IOUT.EQ.1
      CALL GDTPPK('/A/POZADUJES TISK DO PROTOKOLU? (A/N): ',IOUT)
      IF(IOUT.EQ.-2)  GOTO 0202
      LPT = IOUT.EQ.1
0199  CONTINUE
C NEPOZADUJE SE ZADNY TISK
      IF(.NOT.LPT.AND..NOT.LTT)  RETURN
      KK = 1
      RETURN
C
      END
