C POMOCNY TISK PRO PRIPRAVU MERENYCH PRVKU
C=======================================================================
C         1. VERZE  /BREZEN 1985/         VUGTK
C
      SUBROUTINE GDTPM4
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  PPBIT1
C
      CALL GDSSTR(2,2)
      WRITE(GSGDPT,10)
10    FORMAT('0MERENE PRVKY SE VYBIRAJI Z DATOVE ZAKLADNY')
0102  IF(PPBIT1(PK,1).NE.0)  GOTO 0199
         CALL GDSSTR(2,0)
         WRITE(GSGDPT,101)
101      FORMAT('0VYBER ZAMER JE RIZEN OPERATOREM')
0199  CONTINUE
C
      END
