C VYPOCET MATICE VAHOVYCH KOEFICIENTU PRO SOURADNICE
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C       * 5. VERZE      /ZARI 1989/             VUGTK      ALES CEPEK
C
      SUBROUTINE GDTQYX(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      CHARACTER*(*) RET
      PARAMETER (RET=
     / 'MATICE VAHOVYCH KOEFICIENTU PRO SOURADNICE URCOVANYCH BODU:')
      INTEGER  I,J,ISOU,IBOD,EN,II,IQ,UB2
      PARAMETER  (EN=24)
      REAL  GDTSKS
      INTEGER*1  ZAHL(EN),TYP,CBOD(13)
      CHARACTER*(EN) CZAHL
      EQUIVALENCE (CZAHL,ZAHL)
1     FORMAT(I3,' ... ',13A1,'(',A1,')')
C*2   FORMAT(/1X,<EN>A1/X,<II>('='))
2     FORMAT(/1X,24A1/1X,24A1)
117   FORMAT(4(I4,':',E12.5,1X))
118   FORMAT('0UPOZORNENI: VYPOCTENA MATICE BUDE REGISTROVANA',
     /' POUZE V PROTOKOLU'/)
C
      WRITE(ITT,118)
      CALL GDSSTR(0,0)
      CALL GDTTHL(GSGDPT,RET)
      UB2 = 2*URCBOD
      ISOU = 1
0302  IF(ISOU.GT.UB2)  GOTO 0399
         CALL GDTSTB(POCORP+ISOU,IBOD,TYP)
         CALL GDTEXT(IBOD,CBOD)
C*       ENCODE(EN,1,ZAHL)  ISOU,CBOD,TYP
         WRITE(CZAHL,1)     ISOU,CBOD,TYP
         CALL GDSMEZ(ZAHL(3),EN-2,II)
         II = II + 2
         CALL GDSSTR(3,2)
C*       WRITE(GSGDPT,2)  ZAHL
         WRITE(GSGDPT,2)  ZAHL, ('=',J=1,II)
         IQ = ISOU
0402     IF(IQ.GT.UB2)  GOTO 0499
            CALL GDSSTR(1,0)
            WRITE(GSGDPT,117)
     /      (J,GDTSKS(AW,POCPOZ+POCORP+ISOU,POCPOZ+POCORP+J),J=IQ,
     /      MIN(UB2,IQ+3))
            IQ = IQ + 4
            GOTO 0402
0499     CONTINUE
         ISOU = ISOU + 1
         GOTO 0302
0399  CONTINUE
      RETURN
C
      END
