C REDAKCE SEZNAMU MERENYCH PRVKU - SEZMER
C=======================================================================
C         1. VERZE  /CERVEN 1984/         VUGTK
C
      SUBROUTINE GDTRMP
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  PCST,PDELEK,PSMERU,PPBIT1,II,PRVNIS,IER,GDTSUM
      INTEGER*1  S(13),C(13)
      DOUBLE PRECISION  OPOS,YPAR(2),XPAR(2),DPAR
    7 FORMAT('0V DZ NENI REGISTROVAN OR. POSUN NA STANOVISKU ',13A1)
    8 FORMAT(' Z KLAVESNICE VLOZENA HODNOTA Z =',F11.6,' [G]')
    9 FORMAT(' VYPOCTENA PRIBLIZNA HODNOTA Z =',F11.6,' [G]')
   11 FORMAT('0ZRUSEN IZOLOVANY SMER ',13A1,' ----> ',13A1)
   12 FORMAT(' VYPOCET POMOCI ZAMERY NA BOD ',13A1,' SELHAL;'/
     /       ' SMER BYL ZRUSEN')
C
      CALL TTZAHL(ITT,'REDAKCE DAT:')
C*    CALL PPINI1('I',MAX,IZOBOD)
      DO 9981 II81=1,MAX
9981     IZOBOD(II81) = 'I'
      POCORP = 0
C
C ZPRACOVANI OSNOV PODLE PRACOVNICH CISEL BODU
C PCST - PRACOVNI CISLO STANOVISKA
C PRVNIS - PRACOVNI CISLO PRVNIHO SMERU V SEZNAMU MERENYCH PRVKU
C POCORP - POCET ORIENTACNICH POSUNU
C PSMERU - POCET SMERU NA STANOVISKU
C PDELEK - POCET DELEK NA STANOVISKU
      DO 0199 PCST=1,SBPOC
      IF(TYPB(PCST).NE.' ')  GOTO 0100
         IZOBOD(PCST) = 'N'
         GOTO 0199
0100  CONTINUE
      PSMERU = 0
      PDELEK = 0
      II = 1
0202  IF(II.GT.SMPOC)  GOTO 0299
0303     IF(CST(II).NE.PCST)  GOTO 0399
0403        IF(TYPP(II).NE.'S')  GOTO 0404
               IF(PSMERU.EQ.0)  PRVNIS = II
               PSMERU = PSMERU + 1
               GOTO 0499
0404        IF(TYPP(II).NE.'D')  GOTO 0499
               PDELEK = PDELEK + 1
0499        CONTINUE
0399     CONTINUE
         II = II + 1
         GOTO 0202
0299  CONTINUE
0503  IF(PSMERU.GT.1)  GOTO 0504
0603     IF(PSMERU.EQ.0)  GOTO 0699
            TYPP(PRVNIS) = ' '
            PSMERU = PSMERU - 1
            CALL GDTEXT(CST(PRVNIS),S)
            CALL GDTEXT(CCI(PRVNIS),C)
            CALL GDSSTR(2,0)
            WRITE(GSGDPT,11)  S, C
            WRITE(ITT   ,11)  S, C
0699     CONTINUE
         SBZ(PCST) = -1D0
         GOTO 0599
0504  IF(SBZ(PCST).GE.0D0)  GOTO 0599
         CALL GDTEXT(PCST,S)
         CALL GDSMEZ(S,13,IOUT)
         CALL GDSSTR(2,2)
         WRITE(GSGDPT,7)  S
         WRITE(ITT   ,7)  S
0703     IF(PPBIT1(PK,3).EQ.0)  GOTO 0704
0802        CALL TTASKD(ITT,
     /      'VLOZ HODNOTU OR. POSUNU [G]: ',IOUT,OPOS,1)
               IF(IOUT.EQ.1.AND.OPOS.GE.0D0.AND.OPOS.LT.4D2)  GOTO 0899
               IF(IOUT.EQ.0)  GOTO 0704
               GOTO 0802
0899        CONTINUE
            CALL GDSSTR(1,0)
            WRITE(GSGDPT,8)  OPOS
            OPOS = OPOS/RO
            GOTO 0799
0704     CONTINUE
            YPAR(1) = SBY(PCST)
            XPAR(1) = SBX(PCST)
            YPAR(2) = SBY(CCI(PRVNIS))
            XPAR(2) = SBX(CCI(PRVNIS))
            CALL NGSMDA(YPAR,XPAR,OPOS,DPAR,IER)
0903        IF(IER.EQ.0)  GOTO 0999
               CALL GDTEXT(CCI(PRVNIS),C)
               CALL GDSSTR(2,0)
               WRITE(GSGDPT,12)  C
               WRITE(ITT   ,12)  C
               TYPP(PRVNIS) = ' '
               PSMERU = PSMERU - 1
               GOTO 0503
0999        CONTINUE
            OPOS = OPOS - PRVEK(PRVNIS)
            IF(OPOS.LT.0D0)  OPOS = OPOS + DVEPI
            CALL GDSSTR(1,0)
            WRITE(GSGDPT,9)  OPOS*RO
            WRITE(ITT   ,9)  OPOS*RO
0799     CONTINUE
         SBZ(PCST) = OPOS
0599  CONTINUE
      IF(SBZ(PCST).GE.0D0)  POCORP = POCORP + 1
1503  IF(PSMERU.LE.0.AND.PDELEK.LE.0)  GOTO 1599
         IZOBOD(PCST) = 'N'
         II = 1
1602     IF(II.GT.SMPOC)  GOTO 1699
            IF(CST(II).EQ.PCST.AND.TYPP(II).NE.' ')
     /      IZOBOD(CCI(II)) = 'N'
            II = II + 1
            GOTO 1602
1699     CONTINUE
1599  CONTINUE
0199  CONTINUE
      CALL GDTKON
      RETURN
C
      END
