C VYPIS SEZNAMU SOURADNIC
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C
      SUBROUTINE GDTSSO(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      CHARACTER*(*) RET
      PARAMETER  (RET='SEZNAM SOURADNIC BODU SITE:',ITRAD=20)
      EXTERNAL  GDTA93
      LOGICAL  WAIT,GDTINC
      INTEGER  I,II
      INTEGER*4 GDTIND
      DOUBLE PRECISION  Y,X
      INTEGER*1  STANOV(13),TYP
94    FORMAT(1X,13A1,3X,A1,2F16.5)
C
      CALL GDTPNV
      IF(KK.EQ.2)  RETURN
0103  IF(.NOT.LPT)  GOTO 0199
         CALL GDSSTR(0,0)
         CALL GDTTHL(GSGDPT,RET)
         CALL GDTA93(GSGDPT)
0199  CONTINUE
0203  IF(.NOT.LTT)  GOTO 0299
         CALL GDTTHL(ITT,RET)
         CALL GDTA93(ITT)
         WAIT = GDTINC(3-ITRAD)
         CITAC = 0
0299  CONTINUE
C PORADOVE CISLO NEZNAME
      I = POCPOZ + POCORP
      DO 100 II=1,SBPOC
         IF(TYPB(II).EQ.' ')  GOTO 100
         CALL GDTEXT(II,STANOV)
         TYP = INTERT(II)
         Y = SBY(II)
         X = SBX(II)
0303     IF(TYP.EQ.'P')  GOTO 0399
            I = I + 1
            Y = Y + 1E-3*AW(GDTIND(I,NARED))
            I = I + 1
            X = X + 1E-3*AW(GDTIND(I,NARED))
0399     CONTINUE
0403     IF(.NOT.LPT)  GOTO 0499
            CALL GDTSTR(1,0,GDTA93)
            WRITE(GSGDPT,94)  STANOV,TYP,Y,X
0499     CONTINUE
0503     IF(.NOT.LTT)  GOTO 0599
            WRITE(ITT   ,94)  STANOV,TYP,Y,X
0603        IF(.NOT.GDTINC(CITAC))  GOTO 0699
               CALL GDTPAU(WAIT)
               IF(I.LT.MARED.AND.WAIT)  CALL GDTA93(ITT)
0699        CONTINUE
0599     CONTINUE
100   CONTINUE
      IF(LTT)  CALL GDTPAU(WAIT)
C
      END
