C SESTAVENI ROVNIC OPRAV
C=======================================================================
C         1. VERZE  /SRPEN 1984/         VUGTK
C       * 5. VERZE      /ZARI 1989/             VUGTK      ALES CEPEK
C
      SUBROUTINE GDTSRO(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      REAL  ZST,YST,XST,ACL
      INTEGER*1  BOD1(13),BOD2(13),TEXT(48)
      CHARACTER*48 CTEXT
      EQUIVALENCE (CTEXT,TEXT)
      INTEGER  CB(3),I,II,IND(5)
      INTEGER*4 GDTIND,IAW
      LOGICAL  WAIT
16    FORMAT('0ULOHA MA PRILISNE PAMETOVE NAROKY')
C
      CALL TTZAHL(ITT,'SESTAVENI ROVNIC OPRAV:')
0203  IF(FLOAT(MARED)*NARED.LE.VIRDIM)  GOTO 0299
         CALL GDSSTR(2,0)
         WRITE(GSGDPT,16)
         WRITE(ITT   ,16)
         WAIT = .TRUE.
         CALL GDTPAU(WAIT)
         KK = 2
         RETURN
0299  CONTINUE
C
C VYNULOVANI AW A VYTVORENI JEDNOTKOVE MATICE VE SPODNI CASTI AW
      DO 100 IAW=1,MARED*NARED
100   AW(IAW) = 0E0
      DO 110 I=1,POCNEZ
110   AW(GDTIND(POCPOZ+I,I)) = 1E0
      POCVAC = 0
      J = 0
      DO 0199 I=1,SMPOC
         IF(TYPP(I).EQ.' ') GOTO 0199
         VAHA(I) = M0/STRCH(I)
         CALL GDTKOE(I,ZST,YST,XST,ACL,IND,IER)
         IF(IER.NE.0) GOTO 9999
         J = J + 1
         AW(GDTIND(J,IND(1))) = ZST
         AW(GDTIND(J,IND(2))) = YST
         AW(GDTIND(J,IND(3))) = XST
         AW(GDTIND(J,IND(4))) = -YST
         AW(GDTIND(J,IND(5))) = -XST
         AW(GDTIND(J,NARED))  = ACL
0199  CONTINUE
      KK = 1
      RETURN
C
9999  CONTINUE
      CALL GDTEXT(CST(I),BOD1)
      CALL GDTEXT(CCI(I),BOD2)
C*    ENCODE(48,1,TEXT) BOD1,BOD2
      WRITE(CTEXT,1)    BOD1,BOD2
1     FORMAT('BODY  ',13A1,' A ',13A1,' JSOU TOTOZNE')
      CALL GDSMEZ(TEXT,48,II)
      CALL GDSSTR(2,0)
      WRITE(GSGDPT,2) (TEXT(I),I=1,II)
      WRITE(ITT   ,2) (TEXT(I),I=1,II)
2     FORMAT(/1X,80A1)
      KK = 2
      RETURN
C
      END
