C POMOCNA PROCEDURA PRO RIZENI STRANKOVANI PROTOKOLU
C======================================================================
C         1. VERZE  /SRPEN 1984/         VUGTK
C
C JRAD, LPAR  VIZ DOKUMENTACE PROCEDURY GDSSTR
C PROC  JMENO PROCEDURY, KTERA BUDE VOLANA PRI PRECHODU NA NOVOU
C       STRANKU (TISK HLAVICKY). PROC MUSI INTERNE ZAJISTIT ODRADKOVANI
C
      SUBROUTINE GDTSTR(JRAD,LPAR,PROC)
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER*1  LPAR
      INTEGER  JRAD,ISTR
      LOGICAL  NOVSTR
      COMMON /GDSTRW/ NOVSTR,ISTR
C
      CALL GDSSTR(JRAD,LPAR)
      IF(NOVSTR)  CALL PROC(GSGDPT)
      RETURN
C
      END
