C POMOCNA PROCEDURA PRO CTENI A HLEDANI BODU V SEZBOD
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C
      SUBROUTINE GDTSCP(VYZVA,CBOD,INTCB,EOF)
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER*1  VYZVA(1),BOD(15),CBOD(13)
      INTEGER  INTCB,IOUT,CISLOB(3),II
      LOGICAL  EOF,NOVY
C
100   INTCB = 0
      CALL TTASKS(ITT,VYZVA,IOUT,BOD,15)
      EOF = IOUT.EQ.-2
      IF(EOF)  RETURN
      IF(IOUT.LE.0)  GOTO 100
      CALL GDSKCB(1,BOD,15,CISLOB,IER)
      IF(IER.EQ.0)  GOTO 200
         CALL TTPUT1(ITT,0,'CHYBNA SPECIFIKACE CISLA BODU:')
         GOTO 100
200   CONTINUE
      CALL GDSKCB(3,CBOD,II,CISLOB,IER)
      CALL GDTHCB(CISLOB,INTCB,.FALSE.,NOVY)
      IF(.NOT.NOVY.AND.TYPB(INTCB).NE.' ')  RETURN
         CALL TTPUT1(ITT,0,'NEEXISTUJICI BOD SITE:')
         GOTO 100
C
      END
