C VYPIS SMERNIKU
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C       * 5. VERZE      /ZARI 1989/             VUGTK      ALES CEPEK
C
      SUBROUTINE GDTSME(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      EXTERNAL  GDTA96
      CHARACTER*(*) RET
      PARAMETER
     / (RET='PREHLED SMERNIKU ODPOVIDAJICICH POZOROVANYM SMERUM:')
      INTEGER*1  POMTYP(MAXMER),POSUN,STANOV(13),CIL(13),BEVS(9)
      CHARACTER*9 CBEVS
      EQUIVALENCE (CBEVS,BEVS)
      INTEGER  I,IOSN,IPOZ,IOPR,J,CIPOZ,IZ,IPS
      LOGICAL  WAIT,NOVOSN,EOF,CHYBA
      REAL  QSIG,QZZ,QZPS,QV,GDTSKS,EVS,MS,MK
      INTEGER*4  GDTIND
      INTEGER    GDTSUM
      DOUBLE PRECISION  SMER
97    FORMAT(A1,13A1,3X,13A1,F14.6,2F9.1,9A1)
971   FORMAT(F9.1)
C
      IF(POCSME.LE.0)  RETURN
      CALL GDTPNV
      IF(KK.EQ.2)  RETURN
      CALL GDTPR3
      IF(POCSME.LE.0)  RETURN
      CALL PPMOV1(1,TYPP,1,POMTYP,1,SMPOC)
      DO 100  I=1,SMPOC
100   IF(TYPP(I).EQ.'D')  TYPP(I) = ' '
0103  IF(.NOT.LPT)  GOTO 0199
         CALL GDSSTR(0,0)
         CALL GDTTHL(GSGDPT,RET)
         CALL GDTA96(GSGDPT)
0199  CONTINUE
0203  IF(.NOT.LTT)  GOTO 0299
         CALL GDTTHL(ITT,RET)
         WAIT = .TRUE.
C POCET ZPRACOVANYCH OSNOV SMERU
         IOSN = 0
0299  CONTINUE
      CALL GDTOS1
0302  CALL GDTOSN(IPOZ,IOPR,NOVOSN,EOF)
      IF(EOF)  GOTO 0399
0403     IF(.NOT.NOVOSN)  GOTO 0499
            POSUN = '0'
            CALL GDTEXT(CST(IPOZ),STANOV)
0503        IF(.NOT.LPT)  GOTO 0599
               J = 4
               CIPOZ = CCI(IPOZ)
               DO 500 I=1,SMPOC
500            IF(CCI(I).EQ.CIPOZ.AND.TYPP(I).NE.' ')  J = J + 1
               CALL GDTSTR(1,J,GDTA96)
0599        CONTINUE
0603        IF(.NOT.LTT)  GOTO 0699
               IOSN = IOSN + 1
               IF(IOSN.NE.1)  CALL GDTPAU(WAIT)
               IF(WAIT)  CALL GDTA96(ITT)
0699        CONTINUE
0499     CONTINUE
         CALL GDTEXT(CCI(IPOZ),CIL)
         IZ = POCPOZ
         DO 400 I=1,CST(IPOZ)
400      IF(SBZ(I).GE.0D0)  IZ = IZ + 1
         IPS = IPOZ - GDTSUM(POMTYP,IPOZ,' ')
         QZZ = GDTSKS(AW,IZ,IZ)
         QZPS= GDTSKS(AW,IZ,IPS)/ABS(VAHA(IPOZ))
         QPS = GDTSKS(AW,IPS,IPS)/(VAHA(IPOZ)**2)
         QV  = 1E0 - GDTSKS(AW,IPS,IPS)
         QSIG= QZZ + 2E0*QZPS + QPS
         EVS = 0E0
         CHYBA = QV.LT.0.0975
         IF(CHYBA)  GOTO 401
         EVS = AW(GDTIND(IPS,NARED))/ABS(QV)
         EVS = EVS*(ABS(1E0-QV)/ABS(VAHA(IPOZ))+GDTSKS(AW,IZ,IPS))
401      CONTINUE
         SMER = (AW(GDTIND(IZ,NARED)) +
     /          AW(GDTIND(IPS,NARED))/ABS(VAHA(IPOZ)) )*1E-4 +
     /          (SBZ(CST(IPOZ)) + PRVEK(IPOZ))*RO
         IF(SMER.LT.0D0)  SMER = SMER + 4D2
402      IF(SMER.GT.4D2)  SMER = SMER - 4D2
         IF(SMER.GE.4D2)  GOTO 402
         MS = M0AKT*SQRT(ABS(QSIG))
         MK = KPRST*MS
C*       ENCODE(9,971,BEVS)  EVS
         WRITE(CBEVS,971)    EVS
         IF(CHYBA)  CALL PPMOV1(1,'       - ',1,BEVS,1,9)
0703     IF(.NOT.LPT)  GOTO 0799
            CALL GDTSTR(1,0,GDTA96)
            WRITE(GSGDPT,97)  POSUN,STANOV,CIL,SMER,MS,MK,BEVS
0799     CONTINUE
0803     IF(.NOT.LTT)  GOTO 0899
            WRITE(ITT   ,97)  POSUN,STANOV,CIL,SMER,MS,MK,BEVS
0899     CONTINUE
0903     IF(.NOT.NOVOSN)  GOTO 0999
            POSUN = ' '
C*          CALL PPINI1(' ',13,STANOV)
            DO 9982 II82=1,13
9982           STANOV(II82) = ' '	
0999     CONTINUE
         GOTO 0302
0399  CONTINUE
      IF(LTT)  CALL GDTPAU(WAIT)
      CALL PPMOV1(1,POMTYP,1,TYPP,1,SMPOC)
C
      END
