C POMOCNA PROCEDURA PRO DEFINICI CHARAKTERISTIK UKLADANYCH VELICIN
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C
      SUBROUTINE GDTSUW(TYP)
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER   CS
      LOGICAL   ULZUKS,ULZUKP,ULZTS1,ULZTS2
      INTEGER*1      ULZCHB(MAX),ULZCHS(MAX),ULZCHZ(MAXMER)
      COMMON // ULZUKS,ULZUKP,ULZTS1,ULZTS2,CS,ULZCHB,ULZCHS,ULZCHZ
      INTEGER*1  TYP
      INTEGER  GDTSUM,IOUT,N,NB,NS,NZ
      LOGICAL  ERROR
      ERROR(N) = N.LT.0.OR.N.GT.127
C
      IF(GDTSUM(INTERT,SBPOC,TYP).LE.0)  RETURN
      IF(TYP.EQ.'P')  CALL TTPUT1(ITT,1,'PEVNE BODY:')
      IF(TYP.EQ.'U')  CALL TTPUT1(ITT,1,'URCOVANE BODY:')
      IF(TYP.EQ.'O')  CALL TTPUT1(ITT,1,'OPERNE BODY:')
0102  NB = -1
      CALL TTASKN(ITT,'CHAR. BODU     : ',IOUT,NB,1)
      IF(IOUT.LT.0)  GOTO 0102
      IF(IOUT.EQ.0)  GOTO 0202
      IF(ERROR(NB))  GOTO 0102
0202  NS = -1
      CALL TTASKN(ITT,'CHAR. SOURADNIC: ',IOUT,NS,1)
      IF(IOUT.LT.0)  GOTO 0202
      IF(IOUT.EQ.0)  GOTO 0302
      IF(ERROR(NS))  GOTO 0202
0302  DO 0399 I=1,SBPOC
         IF(INTERT(I).NE.TYP)  GOTO 0399
         IF(NB.GE.0)  ULZCHB(I) = NB
         IF(NS.GE.0)  ULZCHS(I) = NS
0399  CONTINUE
      RETURN
C
      ENTRY GDTSUP
0402  NZ = -1
      CALL TTASKN(ITT,'CHAR.ZAMER: ',IOUT,NZ,1)
      IF(IOUT.LT.0)  GOTO 0402
      IF(IOUT.EQ.0)  RETURN
      IF(ERROR(NZ))  GOTO 0402
      DO 0599 I=1,SMPOC
0599     ULZCHZ(I) = NZ
      RETURN
C
      END
