C SPECIFIKACE UKLADANYCH VELICIN
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C
      SUBROUTINE GDTSUV
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER   CS
      LOGICAL   ULZUKS,ULZUKP,ULZTS1,ULZTS2
      INTEGER*1      ULZCHB(MAX),ULZCHS(MAX),ULZCHZ(MAXMER)
      COMMON // ULZUKS,ULZUKP,ULZTS1,ULZTS2,CS,ULZCHB,ULZCHS,ULZCHZ
      INTEGER  IOUT,TTLENF,I
      LOGICAL  GDTSEZ
124   FORMAT('0VYSLEDKY VYROVNANI MOHOU BYT ULOZENY POUZE DO NEKTEREHO',
     /' Z PRAZDNYCH'/' SEZNAMU DATOVE ZAKLADNY ',70A1)
1241  FORMAT('0ZADANY SEZNAM NENI PRAZDNY')
1     FORMAT('0MUZES ZADAT CHARAKTERISTIKY SPOLECNE PRO JEDNOTLIVE',
     /' KATEGORIE BODU'/' (PEVNE, URCOVANE, OPERNE). PRI UZITI PRAZDNE',
     /' ODPOVEDI BUDE PREVZATA'/' STAVAJICI CHARAKTERISTIKA'/)
C
      CALL TTZAHL(ITT,'ULOZENI VYSLEDKU:')
0100  CALL PPMOV1(1,CHAB,1,ULZCHB,1,SBPOC)
      CALL PPMOV1(1,CHAS,1,ULZCHS,1,SBPOC)
      CALL PPMOV1(1,CHAZ,1,ULZCHZ,1,SMPOC)
      KK = 2
      GOTO 0122
0102  WRITE(ITT,1241)
0112  WRITE(ITT,124)  (SOUBT(I),I=1,TTLENF(SOUBT))
0122  CALL TTASKN(ITT,'CISLO SEZNAMU: ',IOUT,CS,1)
         IF(IOUT.EQ.-1)  GOTO 0112
         IF(IOUT.EQ.-2)  RETURN
         IF(IOUT.LE.0)   GOTO 0122
         IF(CS.LT.1.OR.CS.GT.8)  GOTO 0122
         IF(GDTSEZ(CS))  GOTO 0102
0202  CALL GDTPPK('/A/BUDOU UKLADANY SOURADNICE? (A/N): ',IOUT)
      IF(IOUT.EQ.-2)  GOTO 0122
      ULZUKS = IOUT.EQ.1
      ULZTS1 = .FALSE.
      IF(IOUT.EQ.2)   GOTO 0400
0302  CALL GDTPPK('/A/SE ZACHOVANIM STAVAJICICH CHAR. BODU/SOURADNIC'//
     /' VSECH BODU SITE? (A/N): ',IOUT)
      IF(IOUT.EQ.-2)  GOTO 0202
      ULZTS1 = IOUT.EQ.1
      IF(IOUT.EQ.1)   GOTO 0400
      WRITE(ITT,1)
      CALL GDTSUW('P')
      CALL GDTSUW('U')
      CALL GDTSUW('O')
C
0400  CONTINUE
0402  CALL GDTPPK('/A/BUDOU UKLADANY VYROVNANE SMERY/DELKY? (A/N): ',
     /IOUT)
      IF(IOUT.EQ.-2)  GOTO 0202
      ULZUKP = IOUT.EQ.1
      ULZTS2 = .FALSE.
0502  IF(IOUT.NE.2)  GOTO 0599
         IF(ULZUKS)  KK = 1
         RETURN
0599  CONTINUE
      CALL GDTPPK('/A/SE STAVAJICIMI CHAR. ZAMER? (A/N): ',IOUT)
      IF(IOUT.EQ.-2)  GOTO 0402
      ULZTS2 = IOUT.EQ.1
      KK = 1
      IF(IOUT.EQ.1)  RETURN
      CALL GDTSUP
C
      END
