C PROCEDURA PREVADI INDEX NEZNAME (TJ. INDEX SLOUPCE V MATICI SOUSTAVY
C ROVNIC OPRAV) NA PRACOVNI CISLO BODU A TYP NEZNAME (Z/Y/X)
C=======================================================================
C         1. VERZE  /ZARI 1984/         VUGTK
C
C INDSLO  VSTUPNI PARAMETR, INDEX SLOUPCE V MATICI SOUSTAVY ROVNIC OPRAV
C INDBOD  VYSTUPNI PARAMETR, PRACOVNI CISLO BODU
C TYPNEZ  VYSTUPNI PARAMETR, TYP NEZNAME ('Z'/'Y'/'X')
C
      SUBROUTINE GDTSTB(INDSLO,INDBOD,TYPNEZ)
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  INDSLO,INDBOD,II,JJ,I
      INTEGER*1  TYPNEZ
C
0103  IF(INDSLO.GT.POCORP)  GOTO 0104
         TYPNEZ = 'Z'
         JJ = INDSLO
         II = 0
         DO 100 I=1,SBPOC
            IF(SBZ(I).GE.0D0)  II = II + 1
            IF(II.EQ.JJ)  GOTO 110
100      CONTINUE
110      INDBOD = I
         RETURN
0104  CONTINUE
         TYPNEZ = 'Y'
         IF(MOD(INDSLO-POCORP,2).EQ.0)  TYPNEZ = 'X'
         JJ = (INDSLO-POCORP+1)/2
         II = 0
         DO 200 I=1,SBPOC
            IF(TYPB(I).EQ.'U')  II = II + 1
            IF(II.EQ.JJ)  GOTO 210
200      CONTINUE
210      INDBOD = I
         RETURN
C
      END
