C TISK LEGENDY A POSTUPOVEHO KLICE
C=======================================================================
C         1. VERZE      /ZARI 1984/             VUGTK
C       * 5. VERZE      /ZARI 1989/             VUGTK      ALES CEPEK
C
      SUBROUTINE GDTTLE
C
$INCLUDE: 'GDDCHW.COM'
$INCLUDE: 'GDTSOW.COM'
      INTEGER  PPBIT1,TTLENF,I
      INTEGER*1  TEXT(70)
      CHARACTER CTEXT*70,CPK*10
      EQUIVALENCE( CTEXT,TEXT)
10    FORMAT(
     /' LEGENDA'/
     /' A,B   : POLOOSY STR. ELIPSY CHYB'/
     /' A'',B'' : POLOOSY ELIPSY CHYB PRO ZADANOU KONFID.',
     /' PRAVDEPODOBNOST'/
     /' ALFA  : SMERNIK HLAVNI POLOOSY ELIPSY CHYB'/
     /' DEFEKT: POCET ZAVISLYCH SLOUPCU V MATICI SOUSTAVY ROVNIC OPRAV'/
     /' DIF-D : ROZDIL DVOJIHO VYPOCTU DELEK'/
     /' DIF-P : PRICNA ODCHYLKA ODPOVIDAJICI DIF-SK'/
     /' DIF-SK: ROZDIL DVOJIHO VYPOCTU SMERNIKU'/
     /' EM-D/S: ODHAD SKUTECNE CHYBY MER. DELKY/SMERU')
11    FORMAT(
     /' EV-D/S: ODHAD SKUTECNE CHYBY VYR. DELKY/SMERU'/
     /' EV-SK : ODHAD SKUTECNE CHYBY VYR. SMERNIKU'/
     /' F     : POKLES [%] STR. CHYBY DELKY/SMERU V DUSLEDKU',
     /' VYROVNANI'/
     /'         N ... NEKONTROLOVANY PRVEK SITE'/
     /'         S ... SLABE KONTROLOVANY PRVEK SITE'/
     /' G     : PARAMETR POLOHY BODU DANEHO PRIBLIZ. SOURADNICEMI',
     /'  VZHLEDEM KE')
12    FORMAT(
     /'         KONFID. ELIPSE CHYB'/
     /'         G < 1 ... BOD UVNITR ELIPSY'/
     /'         G = 1 ... BOD NA ELIPSE'/
     /'         G > 1 ... BOD VNE ELIPSY'/
     /' M0    : APRIORNI JEDNOTKOVA STREDNI CHYBA'/
     /' M0''   : EMPIRICKA JEDNOTKOVA STREDNI CHYBA'/
     /' M0''''  : MINIMALNI HODNOTA M0'', KTERE LZE DOSAHNOUT',
     /' VYLOUCENIM  JEDNOHO'/
     /'         POZOROVANI'/
     /' MP    : STR. POLOHOVA CHYBA')
13    FORMAT(
     /' MYX   : STR. SOURADNICOVA CHYBA'/
     /' T     : TYP MERENE VELICINY (D ... DELKA, S ... SMER)'/
     /' TOLABS: TOLERANCE PRO TESTOVANI ABS. CLENU ROVNIC OPRAV',
     /': ROZDIL DELEK,'/
     /'         RESP. PRICNA ODCHYLKA'/
     /' TOLORT: TOLERANCE PRO IDENTIFIKACI ZAVISLYCH SLOUPCU',
     /' V ORTOGONALIZOVA-'/
     /'         NYCH MATICICH'/
     /' TYP   : TYP BODU'/
     /'         P ... PEVNY, U ... URCOVANY, O ... URCOVANY, ZVOLENY',
     /' ZA OPERNY')
14    FORMAT(
     /' V''    : NORMOVANA NEBO STUDENTIZOVANA OPRAVA'/
     /'         K ... PREKROCENA KRITICKA HODNOTA'/
     /'         M ... INDIKACE MAX. ABS. HODNOTY'/
     /' *     : ZVYRAZNENI VELICIN SE VZTAHEM K DELKAM')
2     FORMAT(  'DATOVA ZAKLADNA         : ',30X,' HESLO: ',3A2)
3     FORMAT(1X,'CISLO SEZNAMU (VSTUP)   : ',I1)
4     FORMAT(1X,'SOUBOR INFORMACI O SITI : ',70A1)
5     FORMAT(1X,'NAZEV ULOHY (SITE)      : ',70A1)
C*6   FORMAT( '0POSTUPOVY KLIC          :',I<IPK>)
6     FORMAT( '0POSTUPOVY KLIC          :',A)
7     FORMAT(1X,'BINARNI KOD             : ',2(8I1,1X))
8     FORMAT('0SYSTEMOVE PARAMETRY:'/' M0=',F6.2,'[MM/CC]',
     /9X,'TOLABS=',F9.2,'[MM]',9X,'TOLORT=',E9.2)
9     FORMAT(/1X,70A1)
C
      CALL GDSSTR(1,0)
      IF(PPBIT1(PK,0).EQ.0)  GOTO 100
      WRITE(GSGDPT,10)
      WRITE(GSGDPT,11)
      WRITE(GSGDPT,12)
      WRITE(GSGDPT,13)
      WRITE(GSGDPT,14)
100   CONTINUE
C*    ENCODE(70,2,TEXT)  HESLO
      WRITE(CTEXT,2)     HESLO
      CALL PPMOV1(1,SOUBT,1,TEXT,27,TTLENF(SOUBT))
      WRITE(GSGDPT,9)  TEXT
      WRITE(GSGDPT,3)  ISEZT
      WRITE(GSGDPT,4)  (JMENO(I),I=1,TTLENF(JMENO))
      WRITE(GSGDPT,5)  (ULOHA(I),I=1,TTLENF(ULOHA))
C*    IPK = 2
C*    IF(ABS(PK).GE.10)  IPK = 3
C*    IF(ABS(PK).GE.100)  IPK = 4
C*    IF(ABS(PK).GE.1000)  IPK = 5
C*    IF(ABS(PK).GE.10000)  IPK = 6
      WRITE(CPK,200)  PK
200   FORMAT(I10)
      CALL GDSMEZ(CPK,10,IOUT)
      WRITE(GSGDPT,6)  CPK
      IF(PPBIT1(PK,0).NE.0)  WRITE(GSGDPT,7)  (PPBIT1(PK,I),I=0,15)
      WRITE(GSGDPT,8)  M0,TOLABS,TOL
      CALL GDSSTR(0,0)
C
      END
