C ULOZENI VYSLEDKU
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C
      SUBROUTINE GDTULZ(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL   AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION   AW(VIRDIM)
      INTEGER   CS
      LOGICAL   ULZUKS,ULZUKP,ULZTS1,ULZTS2
      INTEGER*1      ULZCHB(MAX),ULZCHS(MAX),ULZCHZ(MAXMER)
      COMMON // ULZUKS,ULZUKP,ULZTS1,ULZTS2,CS,ULZCHB,ULZCHS,ULZCHZ
C
C SPECIFIKACE UKLADANYCH VELICIN
      CALL GDTSUV
      IF(KK.EQ.2)  RETURN
C VLASTNI ARCHIVACE
      CALL GDTVAR(AW)
      CALL GDTVAS
C
      END
