C VYPIS PREHLEDU OPRAV
C=======================================================================
C         2. VERZE      /RIJEN 1985/         VUGTK      ALES CEPEK
C       * 5. VERZE      /ZARI 1989/             VUGTK      ALES CEPEK
C
      SUBROUTINE GDTVPO(AW,TEST,CALFA)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      LOGICAL  TEST
      REAL  CALFA
      INTEGER  IPOZ,IOPR,I,J,IPOC,CIPOZ
      INTEGER*4 GDTIND
      CHARACTER*(*) RET
      PARAMETER  (RET='PREHLED OPRAV, ANALYZA POZOROVANI:')
      LOGICAL  NOVOSN,EOF,WAIT
      INTEGER*1  POSUN,STANOV(13),CIL(13),TYP,FT,HV,BV1(6),EMEV(17)
      CHARACTER CBV1*6, CEMEV*17
      EQUIVALENCE (CBV1,BV1), (CEMEV,EMEV)
      REAL  QV,GDTSKS,V,V1,VW,EM
      EXTERNAL  GDTA62
64    FORMAT(A1,13A1,1X,13A1,1X,A1,F6.1,A1,F10.3,A1,6A1,17A1)
C
1003  IF(.NOT.LPT)  GOTO 1099
         CALL GDSSTR(0,0)
         CALL GDTTHL(GSGDPT,RET)
         CALL GDTA62(GSGDPT)
1099  CONTINUE
      IF(LTT)  CALL GDTTHL(ITT   ,RET)
      WAIT = .TRUE.
      IPOC = 0
      CALL GDTOS1
0102  CALL GDTOSN(IPOZ,IOPR,NOVOSN,EOF)
      IF(EOF)  GOTO 0199
0203  IF(.NOT.NOVOSN)  GOTO 0204
         POSUN = '0'
         CALL GDTEXT(CST(IPOZ),STANOV)
0603     IF(.NOT.LPT)  GOTO 0699
            J = 4
            CIPOZ = CCI(IPOZ)
            DO 600 I=1,SMPOC
600         IF(CCI(I).EQ.CIPOZ.AND.TYPP(I).NE.' ')  J = J + 1
            CALL GDTSTR(1,J,GDTA62)
0699     CONTINUE
0703     IF(.NOT.LTT)  GOTO 0799
            IPOC = IPOC + 1
            IF(IPOC.NE.1)  CALL GDTPAU(WAIT)
            IF(WAIT)  CALL GDTA62(ITT)
0799     CONTINUE
         GOTO 0299
0204  CONTINUE
         POSUN = ' '
C*       CALL PPINI1(' ',13,STANOV)
         DO 9982 II82=1,13
9982        STANOV(II82) = ' '	
0299  CONTINUE
      CALL GDTEXT(CCI(IPOZ),CIL)
      TYP = TYPP(IPOZ)
      QV  = 1E0 - GDTSKS(AW,IOPR,IOPR)
      F   = 1E2*(1E0-SQRT(ABS(1E0-QV)))
      FT  = ' '
      IF(F.LT.5.0)  FT = 'S'
      IF(F.LT.0.1)  FT = 'N'
      VW = AW(GDTIND(IOPR,NARED))
      V  = VW/ABS(VAHA(IPOZ))
      HV = ' '
      IF(TYP.EQ.'D')  HV = '*'
0303  IF(.NOT.TEST.OR.F.LT.0.1)  GOTO 0304
         V1 = ABS(VW)/(M0AKT*SQRT(ABS(QV)))
C*       ENCODE(7,1,BV1)  V1
         WRITE(CBV1,1)    V1
1        FORMAT(F4.1,2X)
         I = 5
0403     IF(V1.LE.CALFA)  GOTO 0499
            BV1(I) = 'K'
            I = I + 1
0499     CONTINUE
         IF(INDELT.EQ.IOPR)  BV1(I) = 'M'
         GOTO 0399
0304  CONTINUE
         CALL PPMOV1(1,'  -   ',1,BV1,1,6)
0399  CONTINUE
0503  IF(.NOT.((F.GE.5.0).OR.((F.GE.0.1).AND.TEST.AND.(V1.GT.CALFA))))
     / GOTO 0504
         EM = V/ABS(QV)
C*       ENCODE(17,2,EMEV)  EM,EM*ABS(1E0-QV)
         WRITE(CEMEV,2)     EM,EM*ABS(1E0-QV)
2        FORMAT(F8.1,1X,F8.1)
         EMEV(9) = HV
         GOTO 0599
0504  CONTINUE
         CALL PPMOV1(1,'      -        - ',1,EMEV,1,17)
0599  CONTINUE
0803  IF(.NOT.LPT)  GOTO 0899
C *** 2
         CALL GDTSTR(1,0,GDTA62)
         WRITE(GSGDPT,64) POSUN,STANOV,CIL,TYP,F,FT,V,HV,BV1,EMEV
0899  CONTINUE
0903  IF(.NOT.LTT)  GOTO 0999
         WRITE(ITT   ,64) POSUN,STANOV,CIL,TYP,F,FT,V,HV,BV1,EMEV
0999  CONTINUE
      GOTO 0102
0199  CONTINUE
      IF(LTT)  CALL GDTPAU(WAIT)
C
      END
