C VLASTNI ARCHIVACE
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C       * 5. VERZE      /ZARI 1989/             VUGTK      ALES CEPEK
C
      SUBROUTINE GDTVAR(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      INTEGER  POM(3),ERR,CISBOD(7)
      COMMON  /GDDCHW/ POM,ERR,CISBOD
$INCLUDE: 'GDI01W.COM'
$INCLUDE: 'GDI02W.COM'
      INTEGER*1  B01W(46),B02W(38)
      EQUIVALENCE (B01W,Y), (B02W,SMER)
      INTEGER   CS
      LOGICAL   ULZUKS,ULZUKP,ULZTS1,ULZTS2
      INTEGER*1      ULZCHB(MAX),ULZCHS(MAX),ULZCHZ(MAXMER)
      COMMON // ULZUKS,ULZUKP,ULZTS1,ULZTS2,CS,ULZCHB,ULZCHS,ULZCHZ
      INTEGER  TTLENF,I,J,IER,IPRV
      INTEGER*4 GDTIND
      INTEGER  IZAZ
      REAL  STRCHB,GDTSKS
      INTEGER*1  TEXT(72),TEXTD(70),TPRV(MAXMER),S(13),C(13)
      CHARACTER CTEXT*72, CTEXTD*70
      EQUIVALENCE (CTEXT,CTEXTD,TEXT,TEXTD)
1     FORMAT(' DATOVA ZAKLADNA         : ',70A1)
2     FORMAT(' CISLO SEZNAMU (VSTUP)   : ',I1)
3     FORMAT(' CISLO SEZNAMU (VYSTUP)  : ',I1)
4     FORMAT(' SOUBOR INFORMACI O SITI : ',70A1)
5     FORMAT(' NAZEV ULOHY (SITE)      : ',70A1)
6     FORMAT(' VARIANTA RESENI         : ',70A1)
7     FORMAT(' STREDNI CHYBY VYROVNANYCH VELICIN BYLY VYPOCTENY S'//
     /' UZITIM ',8A1/' JEDNOTKOVE STREDNI CHYBY',F8.2,' [MM/CC]')
8     FORMAT(' ZACHOVAVAJI SE EXISTUJICI CHAR. BODU A SOURADNIC')
9     FORMAT(' ZACHOVAVAJI SE EXISTUJICI CHAR. ZAMER')
10    FORMAT(1X,70A1)
126   FORMAT(/1X,70A1/
     /' VYKAZUJE NULOVOU STREDNI CHYBU A PROTO SE NEUKLADA')
1261  FORMAT('VYROVNANY ORIENTACNI POSUN NA BODE ',13A1,22X)
1262  FORMAT('VYROVNANY SMER  ',13A1,' --> ',13A1,23X)
1263  FORMAT('VYROVNANA DELKA ',13A1,' --> ',13A1,23X)
C
      CALL GDSSTR(0,7)
      CALL GDTTHL(GSGDPT,'ULOZENI VYSLEDKU DO DATOVE ZAKLADNY:')
      WRITE(GSGDPT,1)  (SOUBT(I),I=1,TTLENF(SOUBT))
      WRITE(GSGDPT,2)  ISEZT
      WRITE(GSGDPT,3)  CS
      WRITE(GSGDPT,4)  (JMENO(I),I=1,TTLENF(JMENO))
      WRITE(GSGDPT,5)  (ULOHA(I),I=1,TTLENF(ULOHA))
      IF(DEFEKT.GT.0.AND.POB.GT.0)
     /WRITE(GSGDPT,6)  (NAZVAR(I),I=1,TTLENF(NAZVAR))
      WRITE(GSGDPT,10)
      CALL GDT712(GSGDPT)
      CALL GDSSTR(2,0)
      WRITE(GSGDPT,7)  TYPM0,M0AKT
      CALL SCOPY('TYP UKLADANYCH VELICIN;'C,TEXT)
      IF(ULZUKS)  CALL CONCAT(TEXT,' SOURADNICE,'C,TEXT)
      IF(ULZUKS.AND.POCORP.GT.0)  CALL CONCAT(TEXT,' OR.POSUNY,'C,TEXT)
      IF(ULZUKP)  CALL CONCAT(TEXT,' VYR. HODNOTY POZOROVANI,'C,TEXT)
      TEXT(TTLENF(TEXT)) = 0
      CALL GDSSTR(5,0)
      CALL TTPUT1(GSGDPT,1,TEXT)
      WRITE(GSGDPT,10)
      IF(ULZTS1)  WRITE(GSGDPT,8)
      IF(ULZTS2)  WRITE(GSGDPT,9)
      CALL PPMOV1(1,TYPP,1,TPRV,1,SMPOC)
      CISBOD(1) = CS
C
      KK = SOWREC + (MARED*NARED+ISREC-1)/ISREC
      IZAZ = KK
      I = 0
      IF(.NOT.ULZUKS)  I = SBPOC
0102  I = I + 1
      IF(I.GT.SBPOC)  GOTO 0199
      IF(TYPB(I).EQ.' ')  GOTO 0102
         Y = SBY(I)
         X = SBX(I)
         V = 0
         Z = 0
         CHOPOS = -1
         CHBODU = ULZCHB(I)
         CHSOUR = ULZCHS(I)
         CHVYSK = -1
         CALL GDTEXT(I,S)
         CALL GDSKCB(1,S,13,CISBOD(2),IER)
0203     IF(TYPB(I).EQ.'P')  GOTO 0299
            CALL GDTIAW('Y',I,J)
            Y = Y + AW(GDTIND(J  ,NARED))*1E-3
            X = X + AW(GDTIND(J+1,NARED))*1E-3
0299     CONTINUE
0383     IF(SBZ(I).LT.0)  GOTO 0399
            CALL GDTIAW('Z',I,J)
            STRCHB = M0AKT*SQRT(GDTSKS(AW,J,J))
            IF(STRCHB.EQ.0)  GOTO 0384
            Z = SBZ(I) + AW(GDTIND(J,NARED))*1E-4/RO
            CALL GDSRAD(Z)
            CHOPOS = STRCHB
            GOTO 0399
0384     CONTINUE
C*          ENCODE(70,1261,TEXTD)  S
            WRITE(CTEXTD,1261)     S
            CALL GDSMEZ(TEXTD,70,IER)
            CALL GDSSTR(3,0)
            WRITE(GSGDPT,126)  TEXTD
0399     CONTINUE
         IZAZ = IZAZ + 1
         WRITE(GSGDIS,REC=IZAZ)  CISBOD,B01W
         GOTO 0102
0199  CONTINUE
      IZAZ = IZAZ + 1
      WRITE(GSGDIS,REC=IZAZ)  -1
C
      I = 0
      IF(.NOT.ULZUKP)  I = SMPOC
0502  I = I + 1
      IF(I.GT.SMPOC)  GOTO 0599
      IF(TPRV(I).EQ.' ')  GOTO 0502
         SMER   = 0
         DELKA  = 0
         CHSMER = -1
         CHD    = -1
         CHRAD  = ULZCHZ(I)
         CALL GDTEXT(CST(I),S)
         CALL GDTEXT(CCI(I),C)
         CALL GDSKCB(1,S,13,CISBOD(2),IER)
         CALL GDSKCB(1,C,13,CISBOD(5),IER)
0683     CALL GDTVAW('S',I,IPRV,TPRV)
         IF(IPRV.EQ.0)  GOTO 0699
            CALL GDTIAW('P',IPRV,J)
            STRCHB = M0AKT*SQRT(GDTSKS(AW,J,J))/ABS(VAHA(IPRV))
            IF(STRCHB.EQ.0)  GOTO 0684
            SMER   = PRVEK(IPRV) + AW(GDTIND(J,NARED))*1E-4
     /                             /ABS(VAHA(IPRV))/RO
            IF(SMER.GT.DVEPI)  SMER = SMER - DVEPI
            IF(SMER.LT.0D0  )  SMER = SMER + DVEPI
            CHSMER = STRCHB
            GOTO 0699
0684     CONTINUE
C*          ENCODE(70,1262,TEXTD)  S,C
            WRITE(CTEXTD,1262)     S,C
            CALL GDSMEZ(TEXTD,70,IER)
            CALL GDSSTR(3,0)
            WRITE(GSGDPT,126)  TEXTD
0699     CONTINUE
0783     CALL GDTVAW('D',I,IPRV,TPRV)
         IF(IPRV.EQ.0)  GOTO 0799
            CALL GDTIAW('P',IPRV,J)
            STRCHB = M0AKT*SQRT(GDTSKS(AW,J,J))/ABS(VAHA(IPRV))
            IF(STRCHB.EQ.0)  GOTO 0784
            DELKA = PRVEK(IPRV) + AW(GDTIND(J,NARED))*1E-3
     /                            /ABS(VAHA(IPRV))
            CHD   = STRCHB
            GOTO 0799
0784     CONTINUE
C*          ENCODE(70,1263,TEXTD)  S,C
            WRITE(CTEXTD,1263)     S,C
            CALL GDSMEZ(TEXTD,70,IER)
            CALL GDSSTR(3,0)
            WRITE(GSGDPT,126)  TEXTD
0799     CONTINUE
         IZAZ = IZAZ + 1
         WRITE(GSGDIS,REC=IZAZ)  CISBOD,B02W
         GOTO 0502
0599  CONTINUE
      IZAZ = IZAZ + 1
      WRITE(GSGDIS,REC=IZAZ)  -1
      RETURN
C
      END
