C ZPRACOVANI VYBOCUJICICH ABSOLUTNICH CLENU
C======================================================================
C         1. VERZE  /SRPEN 1984/         VUGTK
C
C KK = 1  VYPOCET POKRACUJE
C KK = 2  TOLERANCE PREKROCENA, UKONCENI PROGRAMU
C KK = 3  TOLERANCE PREKROCENA, AKTUALIZACE SOUBORU IS
C
      SUBROUTINE GDTVAC(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      INTEGER  IOUT,PPBIT1
C
      KK = 1
      IF(POCVAC.EQ.0)  RETURN
      CALL GDTDS1(AW,GSGDPT,2)
      CALL GDTDS1(AW,ITT   ,2)
      CALL GDSDAN('/A/BUDES KORIGOVAT VSTUPNI DATA? (A/N): ',IOUT)
0103  IF(IOUT.NE.2)  GOTO 0199
         CALL GDSDAN('/A/MAM UKONCIT VYPOCET? (A/N): ',IOUT)
         KK = 2/IOUT
         RETURN
0199  CONTINUE
C AKTUALIZACE SOUBORU IS
      KK = 3
      RETURN
C
      END
