C VLASTNI ARCHIVACE (2. KROK)
C=======================================================================
C         1. VERZE  /PROSINEC 1984/         VUGTK
C
      SUBROUTINE GDTVAS
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER*1  B01W(46),B02W(38)
      COMMON /GDI01W/ B01W  /GDI02W/ B02W
      INTEGER  POM(3),ERR,CISBOD(7)
      COMMON /GDDCHW/ POM,ERR,CISBOD
      INTEGER  IZAZ,IER
      LOGICAL  CHYBA
127   FORMAT('0PRO NEDOSTATEK PROSTORU V DZ NEBYLO MOZNO NEKTERE',
     /' VELICINY ARCHIVOVAT'/' - OPERACE SELHALA')
128   FORMAT('0VYSLEDKY VYROVNANI BYLY USPESNE ARCHIVOVANY')
C
      CALL GDDUDZ
      CALL GDDOD1(GSGDDZ,SOUBT,.TRUE.,IER)
      CHYBA = .FALSE.
      IZAZ = KK
0102  IZAZ = IZAZ + 1
      READ(GSGDIS,REC=IZAZ)  CISBOD,B01W
      IF(CISBOD(1).LE.0)  GOTO 0199
         CALL GDDVSR
0203     IF(ERR.NE.-5)  GOTO 0299
            CHYBA = .TRUE.
            GOTO 0102
0299     CONTINUE
         CALL GDDKOM(1)
         CALL GDDASR
         GOTO 0102
0199  CONTINUE
0302  IZAZ = IZAZ + 1
      READ(GSGDIS,REC=IZAZ)  CISBOD,B02W
      IF(CISBOD(1).LE.0)  GOTO 0399
         CALL GDDKOM(3)
         CALL GDDVRP
         IF(ERR.EQ.-7)  CHYBA = .TRUE.
         GOTO 0302
0399  CONTINUE
      CALL GDDUDZ
0803  IF(.NOT.CHYBA)  GOTO 0804
         CALL GDSSTR(3,0)
         WRITE(GSGDPT,127)
         WRITE(ITT   ,127)
         GOTO 0899
0804  CONTINUE
         CALL GDSSTR(2,0)
         WRITE(GSGDPT,128)
         WRITE(ITT   ,128)
0899  CONTINUE
      CALL GDDOD1(GSGDDZ,SOUBT,.FALSE.,IER)
      CISBOD(1) = ISEZT
      RETURN
C
      END
