C VYPIS SOURADNIC
C=======================================================================
C         2. VERZE      /RIJEN 1985/         VUGTK      ALES CEPEK
C
      SUBROUTINE GDTVSO(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      CHARACTER*(*)  RET
      PARAMETER  (RET='PREHLED NEZNAMYCH - SOURADNICE:')
      EXTERNAL  GDTA84
      LOGICAL  WAIT,GDTINC
      INTEGER  CITAC,I,II,INDU2,INDU4,INDO2,INDO4,J
      INTEGER*4 GDTIND
      REAL  HU(4),HO(4),MP,KOREKY,KOREKX,MY,MX,GDTSKS,MKONFY,MKONFX,MK
      INTEGER*1  CISLOB(13),TYP
      DOUBLE PRECISION  PRIBLY,PRIBLX,VYROVY,VYROVX
85    FORMAT(/5X,13A1,7X,'TYP: ',A1,20X,'MP =',F8.1/
     /I4,11X,'Y:',F14.5,F10.5,F14.5,F8.1,F8.1/
     /I4,11X,'X:',F14.5,F10.5,F14.5,F8.1,F8.1)
86    FORMAT(/' SOUHRNNE CHARAKTERISTIKY POLOHY PRO MNOZINY VSECH',
     /' URCOVANYCH (U),RESP.'/' JEN OPERNYCH (O) BODU:'//
     /' TYP BODU    STR. POLOHOVA CHYBA[MM]      KOREKCE POLOHY',
     /' VYROVNANIM[MM]'/' ========= PRUM. == MAX. == CISLO BODU',
     /' === PRUM. == MAX. == CISLO BODU'/)
C
      IF(URCBOD.LE.0)  RETURN
      HU(1) =  0E0
      HU(2) = -1E0
      HU(3) =  0E0
      HU(4) = -1E0
      HO(1) =  0E0
      HO(2) = -1E0
      HO(3) =  0E0
      HO(4) = -1E0
0103  IF(.NOT.LPT)  GOTO 0199
         CALL GDSSTR(0,0)
         CALL GDTTHL(GSGDPT,RET)
         CALL GDTA84(GSGDPT)
0199  CONTINUE
0203  IF(.NOT.LTT)  GOTO 0299
         CALL GDTTHL(ITT   ,RET)
         CALL GDTA84(ITT)
         WAIT = GDTINC(-3)
         CITAC = 0
0299  CONTINUE
C INDEX NEZNAME (SOURADNICE Y URCOVANEHO BODU)
      I = POCORP - 1
      DO 100 II=1,SBPOC
      IF(TYPB(II).NE.'U')  GOTO 100
C PORADOVE CISLO NEZNAME
      I = I + 2
      CALL GDTEXT(II,CISLOB)
      TYP = INTERT(II)
      PRIBLY = SBY(II)
      PRIBLX = SBX(II)
      J = POCPOZ+I
      KOREKY = AW(GDTIND(J,NARED))
      KOREKX = AW(GDTIND(J+1,NARED))
      KOREKY = KOREKY*1E-3
      KOREKX = KOREKX*1E-3
      VYROVY = PRIBLY + KOREKY
      VYROVX = PRIBLX + KOREKX
      MY = M0AKT*SQRT(GDTSKS(AW,J,J))
      J = J + 1
      MX = M0AKT*SQRT(GDTSKS(AW,J,J))
      MKONFY = KPRST*MY
      MKONFX = KPRST*MX
      MP = MY**2 + MX**2
      HU(1) = HU(1) + MP
      MP = SQRT(MP)
0303  IF(MP.LE.HU(2))  GOTO 0399
         HU(2) = MP
         INDU2 = II
0399  CONTINUE
      MK = (KOREKY**2 + KOREKX**2)*1E6
      HU(3) = HU(3) + MK
      MK = SQRT(MK)
0403  IF(MK.LE.HU(4))  GOTO 0499
         HU(4) = MK
         INDU4 = II
0499  CONTINUE
0503  IF(TYP.NE.'O')  GOTO 0599
      HO(1) = HO(1) + MP**2
0603  IF(MP.LE.HO(2))  GOTO 0699
         HO(2) = MP
         INDO2 = II
0699  CONTINUE
      HO(3) = HO(3) + MK**2
0703  IF(MK.LE.HO(4))  GOTO 0799
         HO(4) = MK
         INDO4 = II
0799  CONTINUE
0599  CONTINUE
0803  IF(.NOT.LPT)  GOTO 0899
         CALL GDTSTR(4,0,GDTA84)
         WRITE(GSGDPT,85)  CISLOB,TYP,MP,
     /                     I  ,PRIBLY,KOREKY,VYROVY,MY,MKONFY,
     /                     I+1,PRIBLX,KOREKX,VYROVX,MX,MKONFX
0899  CONTINUE
0903  IF(.NOT.LTT)  GOTO 0999
         WRITE(ITT   ,85)  CISLOB,TYP,MP,
     /                     I  ,PRIBLY,KOREKY,VYROVY,MY,MKONFY,
     /                     I+1,PRIBLX,KOREKX,VYROVX,MX,MKONFX
1003     IF(.NOT.GDTINC(CITAC))  GOTO 1099
            CALL GDTPAU(WAIT)
            IF(I.LT.POCNEZ-1.AND.WAIT)  CALL GDTA84(ITT)
1099     CONTINUE
0999  CONTINUE
100   CONTINUE
      HU(1) = SQRT(HU(1)/URCBOD)
      HU(3) = SQRT(HU(3)/URCBOD)
1103  IF(POB.LE.0)  GOTO 1199
      HO(1) = SQRT(HO(1)/POB)
      HO(3) = SQRT(HO(3)/POB)
1199  CONTINUE
1203  IF(.NOT.LPT)  GOTO 1299
         CALL GDSSTR(7,2)
         WRITE(GSGDPT,86)
         CALL GDTVC1(GSGDPT,'U',HU,INDU2,INDU4)
         IF(POB.GT.0)
     /   CALL GDTVC1(GSGDPT,'O',HO,INDO2,INDO4)
1299  CONTINUE
1303  IF(.NOT.LTT)  GOTO 1399
         WRITE(ITT   ,86)
         CALL GDTVC1(ITT   ,'U',HU,INDU2,INDU4)
         IF(POB.GT.0)
     /   CALL GDTVC1(ITT   ,'O',HO,INDO2,INDO4)
         CALL GDTPAU(WAIT)
1399  CONTINUE
C
      END
