C VYPIS ORIENTACNICH POSUNU
C=======================================================================
C         1. VERZE  /ZARI 1984/         VUGTK
C
      SUBROUTINE GDTVOP(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      CHARACTER*(*) RET
      PARAMETER  (RET='PREHLED NEZNAMYCH - ORIENT. POSUNY:',ITRAD=20)
      EXTERNAL  GDTA81
      INTEGER  II,I,INDKOR,J,CITAC
      INTEGER*4 GDTIND
      INTEGER*1  STANOV(13)
      DOUBLE PRECISION  PRIBL,VYROV
      REAL  KOREK,MAXKOR,GDTSKS,MZ,MKONF
      LOGICAL  WAIT,GDTINC
82    FORMAT(I4,2X,13A1,F12.6,F11.6,F12.6,F9.1,F8.1)
73    FORMAT(/
     /' MAX. KOREKCE ORIENT. POSUNU [CC]:',F8.1,
     /' PRO STANOVISKO ',13A1)
C
      IF(POCORP.LE.0)  RETURN
0403  IF(.NOT.LPT)  GOTO 0499
         CALL GDSSTR(0,0)
         CALL GDTTHL(GSGDPT,RET)
         CALL GDTA81(GSGDPT)
0499  CONTINUE
0503  IF(.NOT.LTT)  GOTO 0599
         CALL GDTTHL(ITT   ,RET)
         CALL GDTA81(ITT)
         WAIT = GDTINC(3-ITRAD)
         CITAC = 0
0599  CONTINUE
      MAXKOR = 0E0
      I = 0
      DO 100 II=1,SBPOC
      IF(SBZ(II).LT.0D0.OR.TYPB(II).EQ.' ')  GOTO 100
C PORADOVE CISLO NEZNAME
      I = I + 1
C CISLO STANOVISKA
      CALL GDTEXT(II,STANOV)
C PRIBLIZNA HODNOTA ORIENTACNIHO POSUNU
      PRIBL = SBZ(II)*RO
      KOREK = AW(GDTIND(POCPOZ+I,NARED))
C KOREKCE Z VYROVNANI [CC]
      KOREK = KOREK*1E-4
0103  IF(ABS(KOREK).LE.ABS(MAXKOR))  GOTO 0199
C MAXIMALNI KOREKCE
         MAXKOR = KOREK
         INDKOR = II
0199  CONTINUE
C VYROVNANA HODNOTA
      VYROV = PRIBL + KOREK
      IF(VYROV.LT.0D0) VYROV = VYROV + 4D2
      IF(VYROV.GE.4D2) VYPOV = VYROV - 4D2
      J = POCPOZ + I
C STREDNI CHYBA
      MZ = M0AKT*SQRT(GDTSKS(AW,J,J))
C KONFIDENCNI INTERVAL
      MKONF = KPRST*MZ
0203  IF(.NOT.LPT)  GOTO 0299
         CALL GDTSTR(1,0,GDTA81)
         WRITE(GSGDPT,82)  I,STANOV,PRIBL,KOREK,VYROV,MZ,MKONF
0299  CONTINUE
0303  IF(.NOT.LTT)  GOTO 0399
         WRITE(ITT   ,82)  I,STANOV,PRIBL,KOREK,VYROV,MZ,MKONF
0603     IF(.NOT.GDTINC(CITAC))  GOTO 0699
            CALL GDTPAU(WAIT)
            IF(I.LT.POCORP.AND.WAIT)  CALL GDTA81(ITT)
0699     CONTINUE
0399  CONTINUE
100   CONTINUE
      MAXKOR = MAXKOR*1E4
      CALL GDTEXT(INDKOR,STANOV)
      CALL GDSMEZ(STANOV,13,I)
0703  IF(.NOT.LPT)  GOTO 0799
         CALL GDSSTR(2,0)
         WRITE(GSGDPT,73)  MAXKOR,STANOV
0799  CONTINUE
0803  IF(.NOT.LTT)  GOTO 0899
         WRITE(ITT   ,73)  MAXKOR,STANOV
         CALL GDTPAU(WAIT)
0899  CONTINUE
C
      END
