C DIALOG PRO VOLBU FUNKCE (ANALYZA A TISK VYSLEDKU)
C=======================================================================
C         1. VERZE  /ZARI 1984/         VUGTK
C
      SUBROUTINE GDTWTT(IPAR,IOUT)
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER IPAR,IOUT
C
      WRITE(ITT,1)
1     FORMAT(/)
      GOTO (10,20,30,40)  IPAR
C
10    WRITE(ITT,11)
11    FORMAT(
     /' K DISPOZICI JSOU SKUPINY FUNKCI PRO'/
     /' 1 ... ANALYZU A TISK SMERU/DELEK'/
     /' 2 ... ANALYZU A TISK NEZNAMYCH A JEJICH FUNKCI'/
     /' 3 ... VARIANTNI ZPRACOVANI VOLNE SITE',
     /        ' (JEN PRI NENULOVEM DEFEKTU)'/
     /' 4 ... OSTATNI OPERACE')
      CALL TTASK(ITT,'ZVOL SKUPINU FUNKCI (1-4): ',IOUT)
      RETURN
C
20    WRITE(ITT,21)
21    FORMAT(
     /' PREHLED FUNKCI:'/
     /' 1 ... TEST JEDNOTKOVE STREDNI CHYBY'/
     /' 2 ... TEST A VYPIS PREHLEDU OPRAV, DETEKCE SLABYCH PRVKU SITE,'/
     /'       ODHAD CHYB POZOROVANI'/
     /' 3 ... VYPIS PREHLEDU VYROVNANYCH POZOROVANI')
      CALL TTASK(ITT,'ZVOL FUNKCI (1-3): ',IOUT)
      RETURN
C
30    WRITE(ITT,31)
31    FORMAT(
     /' PREHLED FUNKCI:'/
     /' 1 ... VYPIS PREHLEDU NEZNAMYCH'/
     /' 2 ... VYPIS PREHLEDU STREDNICH CHYB A PARAMETRU ELIPS CHYB'/
     /' 3 ... VYPIS SEZNAMU SOURADNIC'/
     /' 4 ... VYPIS SEZNAMU DELEK A SMERNIKU'/
     /'       VYPOCTENYCH Z VYROVNANYCH SOURADNIC'/
     /' 5 ... VYPIS PREHLEDU SMERNIKU ODPOVIDAJICICH POZOROVANYM',
     /' SMERUM'/
     /' 6 ... VYPOCET MATICE VAH. KOEFICIENTU PRO SOURADNICE'
     /)
      CALL TTASK(ITT,'ZVOL FUNKCI (1-6): ',IOUT)
      RETURN
C
40    WRITE(ITT,41)
41    FORMAT(
     /'  PREHLED FUNKCI:'/
     /'  1 ... ZMENA PARAMETRU PRO STATISTICKOU ANALYZU'/
     /'  2 ... TEST CHYBY Z LINEARIZACE'/
     /'  3 ... OPAKOVANE VYROVNANI S NAHRADOU PRIBLIZNYCH SOURADNIC ',
     /         'VYROVNANYMI'/
     /'  4 ... AKTUALIZACE/VYPIS SOUBORU INFORMACI O SITI'/
     /'  5 ... ANALYZA SIRENI CHYB V SITI'/
     /'  6 ... ULOZENI VYSLEDKU DO DZ'/
     /'  7 ... -'/
     /'  8 ... -'/
     /'  9 ... -'/
     /' 10 ... UKONCENI VYPOCTU')
      CALL TTASK(ITT,'ZVOL FUNKCI (1-10): ',IOUT)
      RETURN
C
      END
