C POMOCNA PROCEDURA GDTZCP PRO TISK ZAHLAVI PREHLEDU ZADANYCH BODU
C (PROCEDURA GDTZCP JE VOLANA POUZE PROCEDUROU GDTZCB)
C=======================================================================
C         1. VERZE  /CERVEN 1984/         VUGTK
C
      SUBROUTINE GDTZCP(I,J)
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  I
      INTEGER*1     J
      LOGICAL  NOVSTR
      COMMON  /GDSTRW/ NOVSTR
1     FORMAT('   CISLO BODU  TYP',23X,'KOMENTAR'/71('='))
C
      IF(I.LT.0)  GOTO 100
      CALL GDSSTR(I,J)
      IF(.NOT.NOVSTR)  RETURN
100   CALL GDSSTR(2,0)
      WRITE(GSGDPT,1)
      RETURN
C
      END
