C ZMENA PARAMETRU PRO STATISTICKOU ANALYZU
C=======================================================================
C         1. VERZE  /RIJEN 1984/         VUGTK
C
      SUBROUTINE GDTZPA
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  IOUT
      REAL  INTPRS,PPRST
      INTEGER*1  INTTYP
4951  FORMAT('0PRI STATISTICKE ANALYZE SE PRACUJE'/
     /' S ',8A1,' JEDNOTKOVOU STREDNI CHYBOU ',F7.2,' [MM/CC]'/
     /' A KONFIDENCNI PRAVDEPODOBNOSTI',F6.2,' %'/
     /' POCET NADBYTECNYCH POZOROVANI:',I6)
50    FORMAT(/' ZMENA PARAMETRU PRO STATISTICKOU ANALYZU')
C
      INTTYP = TYPM0(1)
      INTPRS = PRST
0102  CONTINUE
      WRITE(ITT,4951)  TYPM0,M0AKT,PRST,NADBPO
0203  IF(NADBPO.LE.0)  GOTO 0299
0200     CALL TTASK(ITT,'TYP CHYBY APRIORNI/EMPIRICKA (A/E): ',IOUT)
         IF(IOUT.EQ.-2) GOTO 0199
         IF(IOUT.EQ.0)  GOTO 0299
         IF(IOUT.LT.0)  GOTO 0200
0303     IF(IOUT.NE.1)  GOTO 0304
            CALL PPMOV1(1,'APRIORNI',1,TYPM0,1,8)
            M0AKT = M0
            GOTO 0399
0304     CONTINUE
            CALL PPMOV1(1,' EMPIR. ',1,TYPM0,1,8)
            M0AKT = M01
0399     CONTINUE
0299  CONTINUE
0402  CALL TTASKR(ITT,'KONFIDENCNI PRAVDEPODOBNOST [%]: ',IOUT,PPRST,1)
         IF(IOUT.EQ.-2) GOTO 0199
         IF(IOUT.EQ.0)  GOTO 0499
         IF(IOUT.LE.0)  GOTO 0402
         IF(PPRST.LE.0.OR.PPRST.GE.100)  GOTO 0402
         PRST = PPRST
0499  CONTINUE
      GOTO 0102
0199  CONTINUE
      IF(INTTYP.EQ.TYPM0(1).AND.INTPRS.EQ.PRST)  RETURN
      CALL GDSSTR(2,0)
      WRITE(GSGDPT,50)
C
      END
