C ZPRACOVANI EXISTUJICIHO SOUBORU INFORMACI O SITI
C=======================================================================
C         1. VERZE      /CERVEN 1984/           VUGTK
C       * 5. VERZE      /ZARI 1989/             VUGTK      ALES CEPEK
C
      SUBROUTINE GDTZES(AW)
C
$INCLUDE: 'GDTSOW.COM'
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      INTEGER  I,IOUT,DOLMEZ(7),TTLENF
      INTEGER*4 POCET,J,K
      REAL  VSTUP(ISREC)
      CHARACTER*40  CHSOUB
      EQUIVALENCE  (CHSOUB,SOUB)
      DATA     DOLMEZ / 0,0,1,2,3,4,0 /
    1 FORMAT(
     /' 1 ... AKTUALIZACE/VYPIS SOUBORU INFORMACI O SITI')
    2 FORMAT(
     /' 2 ... DEFINICE (NOVE) SITE ZADANIM CISEL BODU',
     /' (S VYUZITIM DZ)')
    3 FORMAT(
     /' 3 ... VYHLEDANI V DZ VSECH MERENYCH PRVKU PRO EXISTUJICI',
     /' BODY SITE')
    4 FORMAT(
     /' 4 ... PRIPRAVA K SESTAVENI ROVNIC OPRAV')
    5 FORMAT(
     /' 5 ... SESTAVENI ROVNIC OPRAV')
    6 FORMAT(
     /' 6 ... ANALYZA VYSLEDKU DRIVEJSIHO VYROVNANI (U VOLNYCH SITI'/
     /'       AUTOMATICKY REGULARIZOVANE ULOHY) A PRIP. EXPERIMENTY'/
     /'       S RUZNYMI VARIANTAMI VYROVNANI VOLNE SITE')
    7 FORMAT(
     /' 7 ... UKONCENI VYPOCTU')
   11 FORMAT('0K DISPOZICI JSOU NASLEDUJICI FUNKCE PROGRAMU:')
   17 FORMAT('0SOUBOR  IS  ZALOZEN  : ',2(I2,'.'),I4/
     /       ' NAPOSLEDY KONTAKTOVAN: ',2(I2,'.'),I4)
C* 18 FORMAT('0SOUBOR KORESPONDUJE SE SEZNAMEM C.',I2,'  DZ ',
C*   / <LENF(SOUB)>A1,';'/' ROZPOR SE ZADANIM')
   18 FORMAT('0SOUBOR KORESPONDUJE SE SEZNAMEM C.',I2,'  DZ ',
     / A,';'/' ROZPOR SE ZADANIM')
   19 FORMAT('0SOUBOR JE PORUSEN')
   20 FORMAT('0NAVAZUJICI CINNOSTI JSOU RIZENY PROGRAMEM.')
   21 FORMAT('0ZPRACOVANI ULOHY POKRACUJE FUNKCI:')
  171 FORMAT(' NAZEV ULOHY (SITE)   : ',70A1)
C
      WRITE(ITT,17 )  DVYT,DUZA
C*    WRITE(ITT,171)  (ULOHA(I),I=1,LENF(ULOHA))
      WRITE(ITT,171)  (ULOHA(I),I=1,TTLENF(ULOHA))
C*0103IF(ISEZ.EQ.ISEZT.AND.PPCMP1(SOUB,SOUBT,40).EQ.0)  GOTO 0199
C*+
0103  IF(ISEZ.NE.ISEZT)  GOTO 0109
      DO 100 II=1,40
      I=SOUB(II)
      J=SOUBT(II)
      IF(I.EQ.J)  GOTO 100
      IF(I.GE.ICHAR('a').AND.I.LE.ICHAR('z')) I=I-ICHAR('a')+ICHAR('A')
      IF(J.GE.ICHAR('a').AND.J.LE.ICHAR('z')) J=J-ICHAR('a')+ICHAR('A')
      IF(I.NE.J)  GOTO 0109
100   CONTINUE
      GOTO 0199
0109  CONTINUE
C*-            
C*       WRITE(ITT,18)  ISEZ, (SOUB(I),I=1,LENF(SOUB))
         WRITE(ITT,18)  ISEZ, CHSOUB(:TTLENF(SOUB))
         CLOSE(UNIT=GSGDIS)
         CALL GDDUDZ
         KK = 2
         RETURN
0199  CONTINUE
0203  IF(SS.GE.0.AND.SS.LE.10)  GOTO 0299
         WRITE(ITT   ,19)
         CALL GDSDAN('/A/MAM SOUBOR IS ZRUSIT? (A/N): ',IOUT)
C*       IF(IOUT.EQ.1)  CLOSE(UNIT=GSGDIS,DISPOSE='DELETE')
         IF(IOUT.EQ.1)  CLOSE(UNIT=GSGDIS,STATUS='DELETE')
         IF(IOUT.NE.1)  CLOSE(UNIT=GSGDIS)
         CALL GDDUDZ
         KK = 2
         RETURN
0299  CONTINUE
      CALL GDTDSP
      CALL GDTTLE
C
C*    CALL PPINI1(' ',25,NAZVAR)
      DO 9981 II81=1,25
9981     NAZVAR(II81) = ' '
      CALL GDSSTR(3,2)
      WRITE(GSGDPT,17)  DVYT,DUZA
      CALL GDTBU1(.TRUE.,.FALSE.)
C*    IF(SS.EQ.0)  CALL GDTBUF(
C*   /'V SOUBORU NEJSOU REGISTROVANY ZADNE PRVKY SITE,',0)
C*    IF(SS.GT.0)  CALL GDTBUF(
C*   /'V  IS  JSOU REGISTROVANY BODY SITE,',0)
C*    IF(SS.GT.1)  CALL GDTBUF(' MER. PRVKY,',0)
C*    IF(SS.GT.3)  CALL GDTBUF(' VYSLEDKY 1. KROKU GSO,',0)
      IF(SS.EQ.0)  CALL GDTBUF(
     /'V SOUBORU NEJSOU REGISTROVANY ZADNE PRVKY SITE,',47)
      IF(SS.GT.0)  CALL GDTBUF(
     /'V  IS  JSOU REGISTROVANY BODY SITE,',35)
      IF(SS.GT.1)  CALL GDTBUF(' MER. PRVKY,',12)
      IF(SS.GT.3)  CALL GDTBUF(' VYSLEDKY 1. KROKU GSO,',23)
      CALL GDTBU2(1)
      IF(SS.GT.0)  CALL GDTTPT(GSGDPT)
      IF(SS.GT.0)  CALL GDTTPT(ITT)
      WRITE(ITT,11)
      IF(SS.GE.DOLMEZ(1))  WRITE(ITT,1)
      IF(SS.GE.DOLMEZ(2))  WRITE(ITT,2)
      IF(SS.GE.DOLMEZ(3))  WRITE(ITT,3)
      IF(SS.GE.DOLMEZ(4))  WRITE(ITT,4)
      IF(SS.GE.DOLMEZ(5))  WRITE(ITT,5)
      IF(SS.GE.DOLMEZ(6))  WRITE(ITT,6)
      IF(SS.GE.DOLMEZ(7))  WRITE(ITT,7)
      WRITE(ITT,20)
0302  CALL TTASK(ITT,'ZVOL CISLO FUNKCE (1-7): ',IOUT)
         IF(IOUT.GT.0.AND.SS.GE.DOLMEZ(MAX0(1,IOUT)))  GOTO 0399
         GOTO 0302
0399  CONTINUE
      CALL GDSSTR(3,3)
      WRITE(GSGDPT,21)
      GOTO (0403,0404,0405,0406,0407,0408,0409)  IOUT
0403  WRITE(GSGDPT,1)
      KK = 4
      RETURN
0404  WRITE(GSGDPT,2)
C*    CALL PPINI2(0,,SBPOC,PEVBOD,URCBOD,POCBOD,SMPOC,POCSME,POCDEL,
C*   /               POCPOZ,POCORP)
      SBPOC  = 0
      PEVBOD = 0
      URCBOD = 0
      POCBOD = 0
      SMPOC  = 0
      POCSME = 0
      POCDEL = 0
      POCPOZ = 0
      POCORP = 0
      SS = 0
      KK = 1
      RETURN
0405  WRITE(GSGDPT,3)
C*    CALL PPINI2(0,,SMPOC,POCSME,POCDEL,POCPOZ,POCORP)
      SMPOC  = 0
      POCSME = 0
      POCDEL = 0
      POCPOZ = 0
      POCORP = 0
      SS = 1
      KK = 1
      RETURN
0406  WRITE(GSGDPT,4)
      SS = 2
      KK = 1
      RETURN
0407  WRITE(GSGDPT,5)
      SS = 3
      KK = 1
      RETURN
0408  CALL GDSSTR(3,0)
      WRITE(GSGDPT,6)
      POCET = MARED
      POCET = POCET*NARED
C CITAC ZAZNAMU V SOUBORU IS
      J     = SOWREC
C CITAC PRVKU V POLI AW
      K     = 0
8102  J = J + 1
      READ(GSGDIS,REC=J)  VSTUP
      DO 8100 I=1,ISREC
      K = K + 1
      IF(K.GT.POCET)  GOTO 8199
8100  AW(K) = VSTUP(I)
      IF(K.LT.POCET)  GOTO 8102
8199  CONTINUE
      SS = 4
      KK = 1
      RETURN
0409  WRITE(GSGDPT,7)
      KK = 3
      RETURN
C
      END
