C ZPRACOVANI BODU (PEVNYCH/URCOVANYCH)
C=======================================================================
C         1. VERZE      /CERVEN 1984/           VUGTK
C       * 5. VERZE      /KVETEN 1990/           VUGTK      ALES CEPEK
C
C VYZVA   VSTUPNI RETEZEC, TEXT VYZVY PRO VLOZENI CISLA
C         PEVNEHO/URCOVANEHO BODU
C TYP     VSTUPNI PARAMETR, TYP BODU ('P'/'U')
C ITER    VSTUPNI LOGICKA PROMENNA, POVOLUJE ZADAVAT CISLA VICE BODU
C         POSTUPNE BEHEM JEDNOHO VOLANI PROCEDURY
C CISBOD  (VIZ COMMON/GDDCHW/) JE-LI CINNOST PROCEDURY UKONCENA
C         V DIALOGU ODPOVEDI CTRL/Z, OBSAHUJE CISBOD NEDEFINOVANE
C         HODNOTY, JINAK ZUSTAVA ZACHOVAN POSLEDNI STAV (TJ. NAVRAT
C         PO ZPRACOVANI JEDNOHO BODU PO VOLANI PROCEDURY S HODNOTOU
C         PARAMETRU ITER=.FALSE.)
C
      SUBROUTINE GDTZCB(VYZVA,TYP,ITER)
C
$INCLUDE: 'GDTSOW.COM'
      INTEGER  IOUT,I,II,IK,CITAC,INDEX
      PARAMETER  (N=15, M=12)
      INTEGER*1  VYZVA(1),TYP,TEXT(N),ZNAK,POM(M)
      CHARACTER*(M) CPOM
      EQUIVALENCE (CPOM,POM)
      LOGICAL  TEST,NOVY,ITER
      DOUBLE PRECISION  YX(2)
      INTEGER  PPP,ERR,CISBOD
      COMMON /GDDCHW/  PPP(3),ERR,CISBOD(7)
$INCLUDE: 'GDI01W.COM'
C JPF TEST PRO TESTOVANI PRIPUSTNE HODNOTY CHARAKTERISTIKY
      TEST(IK) = IK.GE.0 .AND. IK.LE.127
    2 FORMAT(/
     / ' SIT SE DEFINUJE POSTUPNYM ZADANIM VSECH BODU',
     / ' SITE (VCETNE ORIENTACNICH BODU).'/
     / ' ROZLISUJI SE  P E V N E  BODY, JEJICHZ SOURADNICE',
     / ' SE VYROVNANIM NEMENI A'/
     / ' U R C O V A N E  BODY (VSECHNY OSTATNI). PROGRAMEM',
     / ' LZE VYROVNAT I SITE BEZ'/
     / ' PEVNYCH BODU, PRIPADNE S POCTEM PEVNYCH BODU, KTERY',
     / ' NESTACI K JEDNOZNACNE'/
     / ' LOKALIZACI SITE V SOURADNICOVE SOUSTAVE (VOLNE SITE)'/
     / )
    3 FORMAT(1X,015A1,'-   EXISTUJICI BOD SITE')
    4 FORMAT('0CHYBNA SPECIFIKACE CISLA BODU'/)
    5 FORMAT('0BOD NEMA SOURADNICE'/)
    6 FORMAT(1X,015A1,A1)
    7 FORMAT('0SEZNAM BODU JE OBSAZEN - DALSI BODY NELZE UKLADAT'/)
    8 FORMAT('0BOD NENI REGISTROVAN V DATOVE ZAKLADNE'/)
    9 FORMAT(1X,015A1,
     / '-   BOD NENI REGISTROVAN V DZ NEBO NEMA SOURADNICE')
   10 FORMAT('CH.SOUR.:',I3)
   11 FORMAT(1X,015A1,A1,
     / '   SOURADNICE VLOZENY Z KLAVESNICE:'/
     / 1X,015X,4X,'Y = ',F11.3,'   X = ',F11.3,'  ',013A1)
   12 FORMAT(1X,015X,4X,'CH.BODU.:',I3)
C
      CISBOD(1) = ISEZ
      CITAC = 0
0502  CONTINUE
      CITAC = CITAC + 1
      IF(.NOT.ITER.AND.CITAC.GT.1)  RETURN
0703  IF(SBPOC.LT.MAXBOD)  GOTO 0799
         CALL GDTZCP(3,0)
         WRITE(GSGDPT,7)
         WRITE(ITT   ,7)
         CISBOD(2) = -1
         RETURN
0799  CONTINUE
0202  CONTINUE
         CALL TTASKS(ITT,VYZVA,IOUT,TEXT,N)
         CISBOD(2) = -1
         IF(IOUT.EQ.-2)  RETURN
         IF(IOUT.EQ.-1)  WRITE(ITT,2)
         IF(IOUT.LE.0)   GOTO 0202
         CALL GDSKCB(1,TEXT,N,CISBOD(2),IER)
         IF(IER.EQ.0)  GOTO 0299
         WRITE(ITT,4)
         GOTO 0202
0299  CONTINUE
      DO 0399 I=14,N
0399  TEXT(I) = ' '
      CALL GDSKCB(3,TEXT,II,CISBOD(2),IER)
      CALL GDTHCB(CISBOD(2),INDEX,.TRUE.,NOVY)
0603  IF(NOVY)  GOTO 0699
         CALL GDTZCP(1,0)
         WRITE(GSGDPT,3)  TEXT
         WRITE(ITT   ,3)  TEXT
         CISBOD(2) = -1
         GOTO 0502
0699  CONTINUE
C
C NEPRACUJE-LI SE S DATOVOU ZAKLADNOU, NASLEDUJE PRECHOD NA DIALOG
C PRO VLOZENI SOURADNIC Z KLAVESNICE
      Z = -1D0
      CHBODU = -1
      CHSOUR = -1
      IF(.NOT.PRASDZ)  GOTO 0902
      CALL GDDHSR
C
C NENI-LI BOD NALEZEN V DATOVE ZAKLADNE, NASLEDUJE TISK ZPRAVY A
C PRECHOD NA DIALOG PRO VLOZENI SOURADNIC Z KLAVESNICE
1103  IF(ERR.GE.0)  GOTO 1199
         WRITE(ITT,8)
         GOTO 0902
1199  CONTINUE
      CALL GDDKOM(2)
      IF(CHOPOS.LT.0E0)  Z = -1D0
0803  IF(CHSOUR.LT.0)  GOTO 0899
C*       IF(CHOPOS.LT.0E0)  Z = -1D0   ****** TEST PRESENUT ZA GDDKOM
         CALL GDTZCP(1,0)
         WRITE(GSGDPT,6)  TEXT, TYP
C  NASLEDUJE PRECHOD NA ULOZENI INFORMACI O BODU
         GOTO 3000
0899  CONTINUE
      WRITE(ITT,5)
C
0902  CALL TTASKD(ITT,'VLOZ SOURADNICE [Y,X]: ',IOUT,YX,2)
         IF(IOUT.LT.0)  THEN
            WRITE(ITT,9021)
9021        FORMAT(/
     /      ' <   >  ...  BOD NEBUDE ZPRACOVAN'/)
         END IF
         Y = YX(1)
         X = YX(2)
         IF(IOUT.EQ.2.AND.DMAX1(DABS(Y),DABS(X)).LT.1D7)  GOTO 0999
1003     IF(IOUT.NE.0)  GOTO 1099
            CALL GDTZCP(1,0)
            WRITE(GSGDPT,9)  TEXT
            SBZ(INDEX) = -1D0
            TYPB(INDEX) = ' '
            GOTO 0502
1099     CONTINUE
         GOTO 0902
0999  CONTINUE
1503  IF(CHBODU.GE.0)  GOTO 1599
1602     CALL TTASKN(ITT,'CHARAKTERISTIKA BODU: ',IOUT,II,1)
            IF(IOUT.EQ.0)  II = 0
         IF(IOUT.LT.0.OR..NOT.TEST(II))  GOTO 1602
         CHBODU = II
1599  CONTINUE
1703  IF(CHSOUR.GE.0)  GOTO 1799
1802     CALL TTASKN(ITT,'CHARAKTERISTIKA SOURADNIC: ',IOUT,II,1)
            IF(IOUT.EQ.0)  II = 0
1899     IF(IOUT.LT.0.OR..NOT.TEST(II))  GOTO 1802
         CHSOUR = II
1799  CONTINUE
      DO 2099 I=1,M
2099  POM(I) = ' '
C*    IF(CHSOUR.GT.0)  ENCODE(M,10,POM)  CHSOUR
      IF(CHSOUR.GT.0)  WRITE(CPOM,10)    CHSOUR
      CALL GDTZCP(2,1)
      WRITE(GSGDPT,11)  TEXT,TYP,Y,X,POM
2103  IF(CHBODU.LE.0)  GOTO 2199
         CALL GDTZCP(1,0)
         WRITE(GSGDPT,12)  CHBODU
2199  CONTINUE
C
C ULOZENI INFORMACI O BODU DO SEZNAMU BODU (SEZBOD)
C HODNOTA INDEX BYLA NASTAVENA PRI HLEDANI/UKLADANI CISLA BODU
3000  SBY(INDEX)  = Y
      SBX(INDEX)  = X
      SBZ(INDEX)  = Z
      CHAB(INDEX) = CHBODU
      CHAS(INDEX) = CHSOUR
      TYPB(INDEX) = TYP
C
      GOTO 0502
C
      END
