C PROGRAM  GETU03  PRO VYROVNANI MISTNI TRIGONOMETRICKE SITE
C=======================================================================
C         3. VERZE      /PROSINEC 1985/         VUGTK      ALES CEPEK
C         4. VERZE      /ZARI 1986/             VUGTK      ALES CEPEK
C-----------------------------------------------------------------------
C       * 5. VERZE      /ZARI 1989/             VUGTK      ALES CEPEK
C
      PROGRAM GETU03
C
C KOMUNIKACNI OBLAST DATOVE ZAKLADNY
$INCLUDE: 'GDDCHW.COM'
C
$INCLUDE: 'GDTSOW.COM'
C
      CHARACTER*6  VERZE
      COMMON  /TTEXIW/ VERZE
C
      REAL  AW
C*    VIRTUAL  AW(VIRDIM)
      DIMENSION  AW(VIRDIM)
      INTEGER  ISTRW(50)
      COMMON /GDSTRW/ ISTRW
C      
C UVODNI INICIALIZACE
      ITT    = 1
      GSGDDZ = 2
      GSGDPT = 3
      GSGDIS = 4
      GSGDVV = 7
      VERZE = 'VXX.01'
      CALL GDTINI
C
C UVODNI DIALOG A INICIALIZACE PROMENNYCH
C KK = 1  NEEXISTUJE SOUBOR IS INFORMACI O SITI
C KK = 2  UKONCENI PROGRAMU
C KK = 3  EXISTUJE SOUBOR IS INFORMACI O SITI
801   CALL GDTUVO
      GOTO (900,99900,802)  KK
C
C ZPRACOVANI EXISTUJICIHO SOUBORU INFORMACI O SITI
C KK = 1  NASLEDUJE ZPRACOVANI PODLE SS
C KK = 2  NESOUHLAS MEZI ZADANYMI UDAJI A UDAJI V SOUBORU IS
C KK = 3  UKONCENI PROGRAMU
C KK = 4  AKTUALIZACE SOUBORU INFORMACI O SITI
802   CALL GDTZES(AW)
      GOTO (803,801,99900,804) KK
803   GOTO (900,9011,902,9031,904) SS+1
C
C AKTUALIZACE SOUBORU IS INFORMACI O SITI
C KK = 1  NASLEDUJE ZPRACOVANI PODLE SS
C KK = 2  UKONCENI PROGRAMU
804   CALL GDTASI
      GOTO (805,99900) KK
805   GOTO (900,901,902,903,911) SS+1
C
C DEFINICE SITE
C KK = 1  SIT BYLA DEFINOVANA
C KK = 2  UKONCENI PROGRAMU
900   CALL GDTDFS
      GOTO (901,99900) KK
C
C PRECHOD K PRIPRAVE MERENYCH PRVKU
C KK = 1  MERENE PRVKY BUDOU VYHLEDANY V DATOVE ZAKLADNE
C KK = 2  AKTUALIZACE SOUBORU IS INFORMACI O SITI
C KK = 3  UKONCENI PROGRAMU
901   CALL GDTPM1
      GOTO (9011,804,99900) KK
C
C PRIPRAVA MERENYCH PRVKU
9011  CALL GDTPM2
C
C REDAKCE SEZNAMU MERENYCH PRVKU
902   CALL GDTRMP
C
C REDAKCE SEZNAMU BODU
      CALL GDTRSB
C
C TISK A ANALYZA PARAMETRU SITE
C KK = 1  SIT NENI DEFINOVANA
C KK = 2  AKTUALIZACE SOUBORU IS INFORMACI O SITI
      CALL GDTTPS(AW)
      GOTO (806,804) KK
C  SS=2 NIKDY NENASTANE
806   GOTO (900,804,99900,903) SS+1
C
C PRECHOD K SESTAVENI ROVNIC OPRAV
C KK = 1  SESTAVENI ROVNIC OPRAV
C KK = 2  AKTUALIZACE SOUBORU IS INFORMACI O SITI
C KK = 3  UKONCENI PROGRAMU
903   CALL GDTSR1
      GOTO (910,804,99900) KK
C
9031  CONTINUE
C
C SESTAVENI ROVNIC OPRAV
C KK = 1  ROVNICE SESTAVENY, ZPRACOVANI ABS. CLENU
C KK = 2  TOTOZNE BODY, AKTUALIZACE SOUBORU IS
910   CALL GDTSRO(AW)
      GOTO (807,804) KK
C
C ZPRACOVANI VYBOCUJICICH ABSOLUTNICH CLENU
C KK = 1  VYPOCET POKRACUJE
C KK = 2  TOLERANCE PREKROCENA, UKONCENI PROGRAMU
C KK = 3  TOLERANCE PREKROCENA, AKTUALIZACE SOUBORU IS
807   CALL GDTVAC(AW)
      GOTO (808,99900,804) KK
C
C TISK PREHLEDU MERENYCH DELEK, ORIENTOVANYCH SMERU, ABS.CLENU A VAH
808   CALL GDTDSA(AW)
C
C PRECHOD K RESENI ROVNIC OPRAV
C KK = 1  NASLEDUJE RESENI ROVNIC OPRAV
C KK = 2  AKTUALIZACE SOUBORU IS
C KK = 3  UKONCENI PROGRAMU
      CALL GDTRR1
      GOTO (809,804,99900) KK
C
C RESENI ROVNIC OPRAV
809   CALL GDTRRO(AW)
C
C PRIPRAVA K ANALYZE A TISK VYSLEDKU
904   CALL GDTAT1(AW)
C
C ANALYZA A TISK VYSLEDKU
C KK = 1  UKONCENI PROGRAMU
C KK = 2  AKTUALIZACE SOUBORU IS
C KK = 3  OPAKOVANE VYROVNANI
911   CALL GDTATV(AW)
      GOTO (99900,804,903) KK
C
C UKONCENI PROGRAMU
99900 CALL GDTEXI
C
      END
